### ISSUE TITLE
build error with calligra (krita)

### ISSUE THREAD

**Issue by brothermechanic** [VcDevel/Vc#103]
Hello
I have an error with dev-libs/vc-1.1.0 when i try to build krita
https://bpaste.net/show/ac5dea7b4289
Hope this helps)

**Comment by mattkretz** [comment]
This looks like Krita is expecting Vc 0.7.x, and not Vc 1.x. Do you want to port Krita to newer Vc?

**Comment by brothermechanic** [comment]
Thanks for answer!
No. I don't.
