### ISSUE TITLE
OptimizeForArchitecture.cmake creates bad compiler flags

### ISSUE THREAD

**Issue by DABH** [VcDevel/Vc#105]
I'm using OptimizeForArchitecture.cmake from Vc in another project.  With the current version of the script in master, my CMake (3.4.1) generates malformed compiler flags.  Specifically, I get compiler commands like
```
/usr/bin/c++ -I/include/folders  -march=broadwell -msse2;-msse2 -msse3;-msse3 -mssse3;-mssse3 -msse4.1;-msse4.1 -msse4.2;-msse4.2 -mavx;-mavx -mfma;-mfma -mbmi2;-mbmi2 -mavx2;-mavx2 -mno-sse4a -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi   -o out.o -c /my/code.cpp
```
The problem (this is on Debian 8 with GCC 5.2.0) is the semicolons in the middle of the optimization flags; Linux interprets semicolons as a command separator, so of course, lots of problems happen trying to execute the above.

The semicolons are coming from the flags that are added from different processor macros.

To fix this issue for me, I edited line 532 of OptimizeForArchitecture.cmake to the following:
`list(APPEND "${Vc_ARCHITECTURE_FLAGS} -m${_flag}")`

This gave me the desired result with the generated compiler flags (no semicolons).  I don't know if this is an issue for anyone else or on other platforms, but I thought I would bring this up since it was a problem in my case.  Thanks!

**Comment by mattkretz** [comment]
Thanks for the report. This look indeed very strange. I'll take a look.

**Comment by mattkretz** [comment]
Your "fix" basically disabled the line. Removing it would have had the same effect. The Vc_ARCHITECTURE_FLAGS variable is a list, so all entries in the list need to be separated by semicolons. This way you can easily use the variable with the COMPILE_OPTIONS property (see e.g. tests/CMakeLists.txt on how it's used).
