### ISSUE TITLE
Forbid explicit contruction of Vc::float_v(Vc::uint_v(Vc::One))

### ISSUE THREAD

**Issue by dimula73** [VcDevel/Vc#121]
The code like this should not compile:

`Vc::float_v currentIndices(Vc::int_v::IndexesFromZero());`

(this feature may be activated by a compiler option to not break compatibility with existent Vc 1.0 code)

The problem is that in Vc 0.8 all vectors types were guaranteed to have the same size. So the code
like in the example exists in the wild. When porting to Vc 1.0, this code becomes invalid on some architectures where `Vc::float_v::size() != Vc::int_v::size()`. The resulting vector becomes half-initialized. The bugs like this are very difficult to track down, so an option to forbid such construction would be really handy for developers who port their code to Vc 1.0.

**Comment by mattkretz** [comment]
I have reconsidered my suggestion to use a feature macro to disable the explicit ctors. I think deprecation should be enough to catch the issue.
