### ISSUE TITLE
Vc fails with gcc 6

### ISSUE THREAD

**Issue by axaith** [VcDevel/Vc#125]
Vc fails with gcc 6 like so:

common/storage.h:189:21: error: flexible array member in union
         EntryType m[];

I tested a hello world program like this:

int main() {  union { int a; int b[]; };  return 0;  }

$ g++-5.3.0 -std=c++14 foo.cpp
$

$ g++-6.1.0 -std=c++14 foo.cpp
foo.cpp: In function ‘int main()’:
foo.cpp:3:26: error: flexible array member in union
$

**Comment by tcanabrava** [comment]
diff --git a/common/storage.h b/common/storage.h
index b1398b4..5909466 100644
--- a/common/storage.h
+++ b/common/storage.h
@@ -187,7 +187,7 @@ private:
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wpedantic"
 #endif
-        EntryType m[];
+        EntryType m[0];
 #ifdef __GNUC__
 #pragma GCC diagnostic pop
 #endif

**Comment by mattkretz** [comment]
@tcanabrava Sadly this only resolves the compilation error. But it breaks the ABI of the type. I.e. after this change function arguments would be passed via the stack instead of via SIMD registers. This is a compatibility issue and a performance issue.
However, the solution may be much simpler: Forbid use of this variant of storage implementation and `#ifdef` it out altogether for GCC.

**Comment by peremato** [comment]
Is there a new tag with these changes?

**Comment by mattkretz** [comment]
Sorry, no. I have not even found time to fix it yet. But this one is high priority. Let's see.

**Comment by mattkretz** [comment]
compiles and all tests pass on master now

**Comment by devsk** [comment]
Is there a plan to get 1.3 out with this patch? The issue has been fixed for a while now and 1.3 milestone has no open issues. Why is it not being released? Apologies if these questions are silly and that information is readily available elsewhere.

**Comment by mattkretz** [comment]
Yes, sorry for the long delay. I was/am working on this with high priority. I just closed/moved all 1.3 issues on Tuesday. There's a final failure lurking on the dashboard that I will hopefully fix today, and if all goes well we'll have a 1.3 release today (or tomorrow).

**Comment by devsk** [comment]
Thank you so much for the update. Eagerly waiting!
