### ISSUE TITLE
FindVc.cmake does not ensure libVc.a is found

### ISSUE THREAD

**Issue by kossebau** [VcDevel/Vc#127]
The installed VcConfig.cmake depends on the result of
```
find_library(Vc_LIBRARIES Vc PATHS "${Vc_LIB_DIR}" NO_DEFAULT_PATH)
```
for the value of Vc_LIBRARIES, which potentially might result in NOTFOUND. Not only potentially, but can happen in real world as e.g. the openSuse packagers decided for some reason to split off libVc.a into a package of its own, and even with inverted dependencies from that package onto the package with the headers. So just installing Vc-devel, with the existing cmake checks, would result in cmake reporting "Vc found!", but later complaining about Vc_LIBRARIES being set to NOTFOUND. And finally the linker failing, due to Vc symbols not being resolvable, as expected.
See also
https://build.opensuse.org/package/view_file/openSUSE:Factory/Vc/Vc.spec
https://bugzilla.opensuse.org/show_bug.cgi?id=981131

This could be catched by also passing `REQUIRED_VARS Vc_LIBRARIES` in cmake/FindVc.cmake
```
find_package_handle_standard_args(Vc CONFIG_MODE REQUIRED_VARS Vc_LIBRARIES)
```
which then would allow cmake to deal with this and give the user a better idea what is wrong here.

**Comment by mattkretz** [comment]
Hi @kossebau. Thanks for your analysis. I had always hoped that I never need to change FindVc.cmake. Can you please retest with the original FindVc.cmake and the committed change?
