### ISSUE TITLE
Avoid performing automagic CXXFLAGS detection

### ISSUE THREAD

**Issue by amadio** [VcDevel/Vc#129]
Hello Matthias,

Vc performs automatic detection of CXXFLAGS for the computer where it is being compiled, which breaks compilation of software on one machine to be installed on another. There is a bug on Gentoo Linux filed for this: https://bugs.gentoo.org/show_bug.cgi?id=584118.

Would it be possible to let the user choose the target architecture rather than detect it in CMake?

**Comment by mattkretz** [comment]
Isn't the `TARGET_ARCHITECTURE` variable enough for your purposes? Do you think it should default to 'none' instead of 'auto'?

**Comment by amadio** [comment]
The problem appears not when compiling Vc itself, but when compiling some other code against Vc. The current VcConfig.cmake automatically adds architecture flags into CXXFLAGS, which causes problems when one wants to compile something on one machine to run on another.

Defaulting to `TARGET_ARCHITECTURE=none` may be enough, but what's really important is that the VcConfig.cmake should only populate Vc-specific variables, while leaving standard variables alone, at least by default. I can always call `vc_set_preferred_flags()` after `find_package(Vc)` if that's what I really want. Maybe passing a variable to the function above that will receive the flags would be a good solution. Then, the user could call, say, `vc_get_native_arch_flags(MYCXXFLAGS)` or something similar.

I can probably put up a merge request with a possible solution if you want. Just let me know.

**Comment by mattkretz** [comment]
The intent of VcConfig.cmake is actually to not modify CMAKE_CXX_FLAGS but only to set Vc_DEFINITIONS, Vc_COMPILE_FLAGS, Vc_ARCHITECTURE_FLAGS, and Vc_ALL_FLAGS (which concatenates the preceding three). Anything else is an actual bug and I'd be happy to merge anything that fixes this.
BTW, are you talking about Vc 0.7 by chance? 0.7 is known to be buggy in this regard.

**Comment by amadio** [comment]
No, this is in Vc-1.2.0. I am using Vc for GeantV, so I am maintaining its package in Gentoo Linux.
Take a look at the bug linked above in Gentoo; the culprit seems to be AddCompilerFlag(), called from OptimizeForArchitecture.cmake.

**Comment by mattkretz** [comment]
Yes, AddCompilerFlag by default adds to CMAKE_CXX_FLAGS. But I just grepped through cmake/* (again) and did not find a single issue. OptimizeForArchitecture collects all the -m<...> flags in Vc_ARCHITECTURE_FLAGS. I would rather assume that Krita by default compiles its targets with Vc_ARCHITECTURE_FLAGS.
The thing here seems to be Gentoo specific because of the expectation that make.conf is the only place the defines the compiler flags? If so, then the Gentoo package should patch Krita to default to the make.conf flags instead of the flags determined via the cmake macro.
The user should simply compile with TARGET_ARCHITECTURE=none. This should give him the flags from make.conf only.

**Comment by amadio** [comment]
Vc should not touch CMAKE_CXX_FLAGS when one calls `find_package(Vc)`. That's the same as modifying CXXFLAGS, so this is what the bug is.

As you state yourself above, then intent of VcConfig.cmake is to not modify CMAKE_CXX_FLAGS, but it does, since it includes VcMacros, which includes OptimizeForArchitecture, which calls AddCompilerFlag, which changes the CXXFLAGS by adding things to CMAKE_CXX_FLAGS by default.

**Comment by amadio** [comment]
Sorry, you are right, after digging through a bit more, I found the problem in calligra build system.
