### ISSUE TITLE
Non-commercial clause in spline example is incompatible with the BSD-3-Clause license

### ISSUE THREAD

**Issue by ismail** [VcDevel/Vc#150]
The following files have a non-commercial clause which is incompatible with the project license:

examples/spline/spline.cpp
examples/spline/spline.h
examples/spline/spline2.h
examples/spline/spline3.h

This come up with the license check in openSUSE submission.

**Comment by mattkretz** [comment]
How much of a problem is this? The example builds upon code from a CERN codebase, so I can't just simply change it.

**Comment by ismail** [comment]
Well it's a big problem because even though they are not built and not installed they will end up in src.rpm and will be redistributed. But there is no way to legally redistribute the source code due to the noncommercial clause. See https://people.debian.org/~bap/dfsg-faq.html#no_commercial

**Comment by mattkretz** [comment]
> Permission to [...] distribute this software [...] strictly for non-commercial purposes is hereby granted [...]

Ouch. I see. I see what I can do. Do I have to prepare a new tarball, or can you drop the `spline` directory and build a package?

**Comment by ismail** [comment]
I have to re-create a tarball but that beats the idea of using upstream source urls: https://en.opensuse.org/SourceUrls If you can remove the directory and do a minor release I would be really greatful. Or I can wait for the next release, that's also possible if it's too much work to a release.

Thanks!

**Comment by mattkretz** [comment]
I just asked for a license exception from the original source. I'll wait a bit for an answer and then look into a 1.3.1 release.

**Comment by ismail** [comment]
Any news on this?

**Comment by mattkretz** [comment]
Sorry for taking so long. I got oral permission to change the license, but the person didn't look happy with it and did not give me written permission. So I guess I'll better ax the example (and put it on the wiki or something).

**Comment by mattkretz** [comment]
resolved on master. The spline example has moved to VcDevel/Vc-examples-nonfree

**Comment by ismail** [comment]
Thank you!

**Comment by mattkretz** [comment]
Working on finalizing the 1.3.1 release now
