### ISSUE TITLE
example_scaling_scalar + gcc 6.3.1 :: compilation crash (gcc RSS>10 GiB)

### ISSUE THREAD

**Issue by adriansev** [VcDevel/Vc#155]
80cd657 master, Fedora 25, gcc 6.3.1
-DTARGET_ARCHITECTURE=auto -DBUILD_TESTING=0 -DVc_IMPL=auto -DBUILD_EXAMPLES=1
CPU i5-3570

the compilation crash with : 
[ 70%] Building CXX object examples/scaling/CMakeFiles/example_scaling_scalar.dir/main.cpp.o
c++: internal compiler error: Killed (program cc1plus)

Machine have 16 Gb RAM and the gcc process is killed when has 10+ GB RSS
Switching off examples remove the problem. 
Thank you.

**Comment by mattkretz** [comment]
Thanks for the report. I have seen compilation issues with this example before. This is really annoying, sorry. I'll see what I can do. But I'll probably just disable the target for GCC6.
