### ISSUE TITLE
Relax the requirements on the return types of generator functions passed to datapar constructors

### ISSUE THREAD

**Issue by brycelelbach** [VcDevel/Vc#162]
The requirements on a generator function for the datapar constructor seem overly strict:

https://github.com/VcDevel/Vc/blob/mkretz/datapar/Vc/detail/datapar.h#L212

It currently requires the function to return objects of the value type. It should just be values implicitly convertible to the value type, I think.

**Comment by mattkretz** [comment]
I agree that this can be annoying. I'd be open for allowing the same conversions that the broadcast ctor allows.

**Comment by brycelelbach** [comment]
So, I know we talked briefly about this earlier, but my memory is a little hazy.

LEWG wanted it to be strict to prevent something like passing a double into a datapar<float>? Something like that?

**Comment by mattkretz** [comment]
LEWG didn't discuss the generator constructor, specifically. There's just general guidance to not have narrowing conversions implicit. So we can easily loosen the rules here without having to consult LEWG first.

**Comment by mattkretz** [comment]
this is resolved on the master branch
