### ISSUE TITLE
Do Vc vectors require initialization?

### ISSUE THREAD

**Issue by DavidPfander-UniStuttgart** [VcDevel/Vc#170]
While staring at some assembly I noticed that my c-style array declaration actually translates to code. It looks like its Vc vector variables get initialized. Can I prevent that? 

VTune output, code and assembly, is in the following gist.
https://gist.github.com/DavidPfander-UniStuttgart/852de93d3a26ca2bbd2c295788d56dd8

**Comment by mattkretz** [comment]
The intent in P0214 is that `datapar<T, A> x` is uninitialized. Looks like a 
bug (actually bad QoI) in my implementation. I'll take a look.

**Comment by DavidPfander-UniStuttgart** [comment]
Could you give me a hint, how I could fix this? 
Background: I have a compute kernel where I have 4 small loops caused by this bug that are in a very hot loop. This hurts performance quite a bit (even worse that it doesn't get unrolled despite compile-time known boundaries).

**Comment by mattkretz** [comment]
please try 0214a9c

**Comment by DavidPfander-UniStuttgart** [comment]
Tried it. Unfortunately, the tiny loop are still there.

**Comment by DavidPfander-UniStuttgart** [comment]
I'll create a minimal example after lunch.

**Comment by mattkretz** [comment]
thank you. I'd like to have a unit test for the issue, but I've not come up with a reliable way to test that a certain expression leaves a value uninitialized. After all, testing the objects value is undefined behavior, so a correct test likely has to interpret the assembly...

**Comment by mattkretz** [comment]
OK, I forgot another place where it initializes. I'm on it.

**Comment by DavidPfander-UniStuttgart** [comment]
Looks like it works. Now my application crashes at a totally unrelated piece of code. Sloppy initialization be damned! :)

**Comment by mattkretz** [comment]
alright. I'll close it then

**Comment by DavidPfander-UniStuttgart** [comment]
Hi, after further testing I'm now guessing that the error I thought was unrelated might be related to the changes made to fix this issue.

I'm getting a segfault pushing a datapar variable into a vector.

Unfortunely, this is hard to debug, as I'm getting the error in the context of a normal application run (Debug/Release), but the application with valgrind runs fire (Debug/Release). I'm confused, that never occured to me.

With gdb attached, the following backtrace is displaced:
```
Program received signal SIGSEGV, Segmentation fault.
0x000000000042c98f in Vc::v2::detail::Storage<double, 4ul, Vc::v2::detail::AliasStrategy::VectorBuiltin>::m (i=0, this=0x0) at /home/pfandedd/Vc_head_install/include/Vc/detail/storage.h:430
430	    Vc_INTRINSIC Vc_PURE EntryType m(size_t i) const { return data[i]; }
(gdb) bt
#0  0x000000000042c98f in Vc::v2::detail::Storage<double, 4ul, Vc::v2::detail::AliasStrategy::VectorBuiltin>::m (i=0, this=0x0) at /home/pfandedd/Vc_head_install/include/Vc/detail/storage.h:430
#1  Vc::v2::detail::Storage<double, 4ul, Vc::v2::detail::AliasStrategy::VectorBuiltin>::operator[] (
    i=0, this=0x0) at /home/pfandedd/Vc_head_install/include/Vc/detail/storage.h:429
#2  Vc::v2::detail::subscript_read<Vc::v2::detail::Storage<double, 4ul, Vc::v2::detail::AliasStrategy::VectorBuiltin> > (x=..., i=0)
    at /home/pfandedd/Vc_head_install/include/Vc/detail/datapar_tuple.h:47
#3  0x000000000042c635 in Vc::v2::detail::datapar_tuple<double, Vc::v2::datapar_abi::avx>::operator[] (this=0x0, i=0) at /home/pfandedd/Vc_head_install/include/Vc/detail/datapar_tuple.h:128
#4  0x000000000042b232 in Vc::v2::detail::fixed_size_datapar_impl<4>::get<double, Vc::v2::datapar_abi::avx> (i=0, v=...) at /home/pfandedd/Vc_head_install/include/Vc/detail/fixed_size.h:454
#5  Vc::v2::datapar<double, Vc::v2::datapar_abi::fixed_size<4> >::operator[] (i=0, this=0x0)
    at /home/pfandedd/Vc_head_install/include/Vc/detail/datapar.h:273
#6  Vc::v2::operator<< <double, Vc::v2::datapar_abi::fixed_size<4> > (out=..., v=...)
    at /home/pfandedd/Vc_head_install/include/Vc/detail/ostream.h:97
#7  0x000000000046610d in compute_ilist ()
    at /home/pfandedd/git/AutoTuneTMP/paper/fmm_m2m_interactions/compute_ilist.cpp:256
#8  0x0000000000466ed1 in detail::init_ilist::init_ilist (this=0x67c3d0 <detail::init_ilist_dummy>)
    at /home/pfandedd/git/AutoTuneTMP/paper/fmm_m2m_interactions/compute_ilist.cpp:368
#9  0x0000000000466ad6 in __static_initialization_and_destruction_0 (__initialize_p=1, 
    __priority=65535)
    at /home/pfandedd/git/AutoTuneTMP/paper/fmm_m2m_interactions/compute_ilist.cpp:370
#10 0x0000000000466b54 in _GLOBAL__sub_I_ilist_n ()
    at /home/pfandedd/git/AutoTuneTMP/paper/fmm_m2m_interactions/compute_ilist.cpp:371
#11 0x000000000046af8d in __libc_csu_init ()
#12 0x00007ffff71837bf in __libc_start_main (main=0x423167 <main()>, argc=1, argv=0x7fffffffdd38, 
    init=0x46af40 <__libc_csu_init>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffdd28) at ../csu/libc-start.c:247
#13 0x0000000000422c89 in _start ()
``` 

I'm a bit confused. Sorry, if this turns out to be unrelated.
