### ISSUE TITLE
Including <Vc/Vc> fails in a more complex building environment

### ISSUE THREAD

**Issue by LJPapenfort** [VcDevel/Vc#171]
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | CPU
1.3.2                  | Linux                 | Intel 17.0           | -O2 -avx           | Intel(R) Xeon(R) CPU E5-2680

## Testcase
```cpp
#include <Vc/Vc>
```

## Actual Results
We are trying to couple Vc to our tensor expression templates library (https://bitbucket.org/whiskydevs/tensortemplates) to get the generated expressions to be vectorized automatically. This works out really nicely already if I compile a standalone test, by doing something like this:   
`icpc -std=c++14 -O2 -I path_to_vc/include/ tensor_vectorization_test.cc -L path_to_vc/lib/ -lVc -xavx`  
It compiles fine, generating vectorized code which is performing pretty well.  
The actual problem appears, when I try compile code which is using the templates as part of the Einstein Toolkit (https://einsteintoolkit.org/). For this I included Vc into the infrastructure and try to compile a test file which just includes <Vc/Vc>, to see if including / linking to Vc works.  
The toolkit is configured to use the same compiler and flags, but once it tries to compile the file which is including the Vc headers it fails to compile with the following error:  
```cpp
In file included from path_to_vc/include/Vc/scalar/../common/types.h(377),
                 from path_to_vc/include/Vc/scalar/types.h(28),
                 from path_to_vc/include/Vc/scalar/vector.h(39),
                 from path_to_vc/include/Vc/vector.h(32),
                 from path_to_vc/include/Vc/Vc(30),
                 from path_to_ET/Cactus/arrangements/WhiskyDevs/TensorTemplates/src/tensor_templates.
hh(23),
                 from path_to_ET/Cactus/configs/testing-avx/bindings/include/tensor_templates.hh(4),
                 from path_to_ET/Cactus/arrangements/RelAstro/thc_grsource_templates/src/thc_grsource
.cc(30):
path_to_vc/include/Vc/scalar/../common/vector.h(55): error: name followed by "::" must b
e a class or namespace name
  inline Vector<T, Abi> copysign(Vector<T, Abi> magnitude, Vector<T, Abi> sign);
```
Since it is compiling fine as standalone, something goes wrong when including the Vc headers through the Einstein Toolkit. I know that the problem has to be triggered somewhere in the toolkit, but I'm not sure where and why. To narrow it down, I wonder if someone here could give me a hint into the right direction what exactly breaks down and why.

**Comment by mattkretz** [comment]
Hi, thanks for the feedback and the detailed report. My first guess is that there's a macro defined by the Einstein Toolkit headers that replaces valid Vc code with something invalid. But I'll take a closer look later.

**Comment by LJPapenfort** [comment]
Found a solution by including some ET headers after the Vc headers. I guess you are write and some weird combination of preprocessor statements leads to wrong code substitution.
It is working now, so this can be closed.
