### ISSUE TITLE
Alignment errors with datapar

### ISSUE THREAD

**Issue by DavidPfander-UniStuttgart** [VcDevel/Vc#173]
I'm getting segfaults in movap instructions, likely due to misaligned vector variables.

GDB output for the final state of the application (segfault) can be seen [on imgur](http://imgur.com/a/eWGSx).

If you calculate (%rdx+32) / 32 it turns out to be something.5 => not aligned.

This happens during the initialization of the following simple struct:
```
struct interaction_type
{
    std::uint16_t first;
    std::uint16_t second;
    space_vector x;
    v4sd four;
};
```
and `spacevector` and `v4sd` are defined as 
```
using v4sd = typename Vc::datapar<double, Vc::datapar_abi::fixed_size<4>>;
using space_vector = Vc::datapar<real, Vc::datapar_abi::avx>;
```
To me this looks like a bug in Vc.

I'm using a slightly patched version of `mkretz/datapar` (https://github.com/STEllAR-GROUP/Vc/tree/pfandedd_inlining_AVX512)

I'm also getting other errors always in movap instructions in other parts of the applications.

Adding `alignas(32)` before space_vector and v4sd don't help (I noticed that the `datapar` class aligns its data member `d`).

**Comment by DavidPfander-UniStuttgart** [comment]
Working theory: Possible reason might be that the default initialization doesn't consider alignment.

**Comment by DavidPfander-UniStuttgart** [comment]
Update: After adding a copy constructor that mirrors the implementation of the default copy-constructor, I can narrow down the misaligned access to writing `x = other.x`.
As the asm says `vmovapd %ymm0,0x20(%rax)` (rax=0x7d9f4d0), the write is misaligned.

If have no idea how I can end up with `x` being misaligned. Do you have any ideas?

**Comment by mattkretz** [comment]
It could be a compiler bug, if x is a local variable and alignof(x) is correct. However, if x is dynamically allocated (also as a member of a class, which got instantiated on the heap), then you need C++17. Before 17 the compiler may ignore overalignment.

**Comment by DavidPfander-UniStuttgart** [comment]
All of it is part of a `push_back` into a vector of `interaction_types`. I'll try with c++17.

**Comment by DavidPfander-UniStuttgart** [comment]
At least a recompile with c++1z (gcc 6.3) unfortunately didn't make a difference.

**Comment by mattkretz** [comment]
I don't know whether 6.3 has the necessary changes implemented. But yes, std::vector push_back certainly exhibits the problem. Try Vc's implementation of an allocator with your vector. It supports arbitrary overalignment.

**Comment by DavidPfander-UniStuttgart** [comment]
Ok, looks like your macro Vc_DECLARE_ALLOCATOR(Data) saves me. Thanks so much for your help, that would have taken me ages to figure out.
(gcc 7 implements support for dynamically allocated overaligned types https://gcc.gnu.org/projects/cxx-status.html#cxx11) 

Thanks a lot!
