### ISSUE TITLE
Implement `static_simd_cast` via `x86::convert`

### ISSUE THREAD

**Issue by mattkretz** [VcDevel/Vc#174]
Up to now `static_simd_cast` is implemented as a generator ctor that converts element-wise using `static_cast`. What I've seen from disasm is that compilers don't optimize these. :-(

`detail/x86/convert.h` has an implementation for (all) conversions. The question is just how to correctly dispatch to those implementations, especially for `fixed_size<N>` casts.

**Comment by mattkretz** [comment]
@DavidPfander-UniStuttgart I'm working on a complete cast implementation now. AFAICS you only implemented the one conversion you needed, right?

**Comment by DavidPfander-UniStuttgart** [comment]
Unfortunately yes, I didn't find the time to really work myself into Vc that deeply. Our application code was hurting too badly.

**Comment by mattkretz** [comment]
Sure, np. The generic `fixed_size` implementation for conversions is pretty complicated anyway, so it's probably for the better that you didn't "waste" your time on it. I hope to have something usable for at least SSE and AVX today.
