### ISSUE TITLE
Can masks be initialized using std::vector<bool>?

### ISSUE THREAD

**Issue by invexed** [VcDevel/Vc#178]
Hi,

Is it safe to initialize masks in the following way?

```c++
std::vector<bool, Vc::Allocator<bool>> vec;
// fill vec with some data
auto mask = Vc::Mask<float>{ vec.data() };
```

Thanks.

**Comment by invexed** [comment]
I assume it isn't safe as it doesn't compile.

I'm using the following aliases to specify the type of a tuple of buffers used to initialize a collection of `Vc::Vector`s 

```c++
namespace simd::vector
{
    template<typename T>
    using aligned = std::vector<T, Vc::Allocator<T>>;
}

constexpr auto make_buffers{
    [](const auto& ...members)
    {
        return boost::hana::type_c<
            boost::hana::tuple<
                simd::vector::aligned<
                    typename std::remove_reference_t<
                        decltype(members)
                    >::value_type
                >...
            >
        >;
    }
};

using Buffers = typename decltype(
    boost::hana::unpack(
        boost::hana::members(std::declval<Container>()),
        make_buffers
    )
)::type;
```

This works fine for `Vc::Vector`, but now I need to do something similar for `Vc::Mask`. I can't use `std::vector<bool, Vc::Allocator<bool>>`, and I can't simply use `std::array<bool, Vc::float_v::Size>` since `bool` is not guaranteed a size of 1 byte. What is the best alternative?

I essentially need an aligned buffer type like `std::vector<bool, Vc::Allocator<bool>>` that can be used as a template parameter within a tuple. Would the following work?

```c++
using IntBoolArray = std::array<bool, Vc::int_v::Size>;
using FloatBoolArray = std::array<bool, Vc::float_v::Size>;

alignas(Vc::VectorAlignment) boost::hana::tuple<IntBoolArray, FloatBoolArray> my_tuple;
```
Thanks in advance for any help you can offer.

**Comment by invexed** [comment]
In the end I used `boost::container::vector` instead of `std::vector`.

**Comment by mattkretz** [comment]
This is safe if you ensure that `vec.size()` is large enough. `Vc::Mask` can load from / store to arrays of bool.
