### ISSUE TITLE
Feature request: arithmetic operator overloads between masks and vectors

### ISSUE THREAD

**Issue by invexed** [VcDevel/Vc#179]
The following is a common pattern required by a lot of my SIMD code:

```c++
(vec1 < vec2) * vec3
```

Currently I have to do something like the following to achieve this:
```c++
inline float_v operator*(float_m mask, const float_v& vector)
{
    return iif(mask, Vector::One(), Vector::Zero()) * vector;
}
```

It would be nice to have library support for this, and I'm not convinced the above solution is as efficient as it could be?

**Comment by mattkretz** [comment]
why don't you write `iif(vec1 < vec2, vec3, 0)`? I don't like the bool int promotion. I believe your request encourages rather poor syntax for something that can be expressed much clearer. Especially the multiplication is not really your intent, so it shouldn't be there in the code either.

**Comment by invexed** [comment]
That's fair enough for the multiplication. But what about this:

```c++
(vec1 < vec2) - 4.f
```
or
```c++
4.f - (vec1 < vec2)
```
How could that be expressed more simply?

**Comment by invexed** [comment]
Of course, it's simply

```c++
iif(vec1 < vec2, -3.f, -4.f)
```
and
```c++
iif(vec1 < vec2, 3.f, 4.f)
```
Sorry, I didn't have my thinking cap on today! Thanks for the quick reply anyway.
