### ISSUE TITLE
Workaround the GCC's missing support for std::for_each_n

### ISSUE THREAD

**Issue by twesterhout** [VcDevel/Vc#182]
| Vc version / revision | Operating System | Compiler & Version | Compiler Flags |
|---------------------------|-------------------------|-------------------------|---------------------|
|master | Linux | Clang-6, GCC-7 | -std=c++17|

My concern is about [this piece of code](https://github.com/VcDevel/Vc/blob/master/attic/common/algorithms.h#L208). `libstdc++` doesn't have `std::for_each_n` [implemented](https://stackoverflow.com/a/46468447). So something as simple as this:
```cpp
#include <Vc/Vc>
int main() {}
```
fails to compile with `-std=c++17`. Perhaps something like this:
```cpp
#ifdef Vc_CXX17
#if defined(Vc_GCC)
template <typename InputIt, typename UnaryFunction>
inline enable_if<!std::is_arithmetic<typename InputIt::value_type>::value, UnaryFunction>
simd_for_each_n(InputIt first, std::size_t count, UnaryFunction f)
{
    for (std::size_t i = 0; i < count; ++i, (void)++first) {
        std::invoke(f, *first);
    }
    return first;
}
#else
template <typename InputIt, typename UnaryFunction>
inline enable_if<!std::is_arithmetic<typename InputIt::value_type>::value, UnaryFunction>
simd_for_each_n(InputIt first, std::size_t count, UnaryFunction f)
{
    return std::for_each_n(first, count, std::move(f));
}
#endif
#endif
```
will fix the problem. I can probably create a PR if you'd like.

**Comment by mattkretz** [comment]
Thanks for the detailed report. I'd take that PR. :-)
