### ISSUE TITLE
Using Vc as CMake subproject

### ISSUE THREAD

**Issue by twesterhout** [VcDevel/Vc#188]
| Vc version / revision | Operating System |
|-----|-----|
| master-branch | Linux |

## Background

This is slightly related to #184, but seeing as I have a concrete use case in mind, I decided to put it into a different issue.

I like the [simd proposal](https://wg21.link/p0214) and my project is in development state, so I'm OK with using unstable master branch. Git submodules seem like the easiest solution. I'm also using CMake, so my hope was that a simple `add_subdirectory` should suffice. This brings me to the problem.

## Problem

CMakelists.txt in Vc root directory uses `CMAKE_SOURCE_DIR`:
https://github.com/VcDevel/Vc/blob/master/CMakeLists.txt#L8
https://github.com/VcDevel/Vc/blob/master/CMakeLists.txt#L185
https://github.com/VcDevel/Vc/blob/master/CMakeLists.txt#L312
This means that if I have Vc cloned somewhere in `myproject/external/Vc`, Vc's CMakelists.txt will search for Vc-specific CMake modules in `myproject/cmake` rather than `myproject/external/Vc/cmake`. Using `CMAKE_CURRENT_SOURCE_DIR` in all three places seems to solve the problem.

Again, I can create a small PR if you like.

Thanks,
Tom

**Comment by milianw** [comment]
For the 1.4 branch at least, the `CMAKE_SOURCE_DIR` isn't really the only problem. The global `CMAKE_CXX_FLAGS` are modified and also the default `CMAKE_BUILD_TYPE` build flags are changed.

**Comment by amadio** [comment]
I just tested Vc as a subproject (with `add_subdirectory(Vc)`), and I believe at least most of the problems reported above have been fixed. Could you please try again and report if anything else is missing?

**Comment by amadio** [comment]
Fixed by #271.
