### ISSUE TITLE
Vc-1.3.3 with GCC 7.3.0 fails SSE/AVX abi tests

### ISSUE THREAD

**Issue by amadio** [VcDevel/Vc#191]
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | Assembler & Version | CPU
----------------------|------------------|--------------------|----------------|---------------------|----
1.3.3                      |  Gentoo Linux                |  GCC 7.3.0                  |                |                     |

Hi Matthias,

I package Vc for Gentoo Linux, and the CI system there has identified some test failures with Vc-1.3.3 when compiling with GCC 7.3.0. The bug report is at https://bugs.gentoo.org/647988, and the log file with the errors can be seen at https://647988.bugs.gentoo.org/attachment.cgi?id=519982. Here is a summary of the system:

```
=================================================================
                         System Settings
=================================================================
System uname: Linux-4.15.4-x86_64-Intel-R-_Core-TM-_i7-3930K_CPU_@_3.20GHz-with-gentoo-2.4.1
KiB Mem:    65383088 total,  18105392 free
KiB Swap:   67108860 total,  67090172 free
Timestamp of repository gentoo: Sun, 18 Feb 2018 02:06:27 +0000
sh bash 4.4_p19
ld GNU ld (Gentoo 2.29.1 p3) 2.29.1
app-shells/bash:          4.4_p19::gentoo
dev-java/java-config:     2.2.0-r3::gentoo
dev-lang/perl:            5.26.1-r1::gentoo
dev-lang/python:          2.7.14-r1::gentoo, 3.5.4-r1::gentoo
dev-util/cmake:           3.10.2::gentoo
dev-util/pkgconfig:       0.29.2::gentoo
sys-apps/baselayout:      2.4.1-r2::gentoo
sys-apps/openrc:          0.34.11::gentoo
sys-apps/sandbox:         2.12::gentoo
sys-devel/autoconf:       2.69-r4::gentoo
sys-devel/automake:       1.9.6-r4::gentoo, 1.15.1-r1::gentoo
sys-devel/binutils:       2.29.1-r1::gentoo, 2.30::gentoo
sys-devel/gcc:            7.3.0::gentoo
sys-devel/gcc-config:     1.9.1::gentoo
sys-devel/libtool:        2.4.6-r4::gentoo
sys-devel/make:           4.2.1-r1::gentoo
sys-kernel/linux-headers: 4.15::gentoo (virtual/os-headers)
sys-libs/glibc:           2.27-r1::gentoo
```
and the list of tests that failed:
```
96% tests passed, 4 tests failed out of 109

Label Time Summary:
AVX       =  18.62 sec*proc (37 tests)
AVX2      =   0.02 sec*proc (1 test)
SSE       =  18.97 sec*proc (40 tests)
Scalar    =  21.83 sec*proc (28 tests)
other     =   0.01 sec*proc (3 tests)

Total Test time (real) =  59.55 sec

The following tests FAILED:
	101 - test_abi_SSE (Failed)
	102 - test_abi_SSE_AVX (Failed)
	103 - test_abi_AVX (Failed)
	104 - test_abi_AVX2 (Failed)
Errors while running CTest
```

Cheers,
—Guilherme

**Comment by mattkretz** [comment]
I have not been able to reproduce it locally, though I've seen failures on Travis. This is bad (unless the test itself fails and the codegen is fine).

**Comment by mattkretz** [comment]
Does your system compiler imply additional compiler flags that may change code gen (e.g. stack protection)?

**Comment by amadio** [comment]
Hi Matthias, the Gentoo bug should have all this information. If anything is missing, please ask there and Toralf can clarify. I am not in control of the tinderbox system. Thanks.

**Comment by mattkretz** [comment]
According to https://647988.bugs.gentoo.org/attachment.cgi?id=519990, the (normally one instruction) function has an active stack protector. I.e. GCC compiles as if `-fstack-protector-all` were specified (it isn't). That's just crazy and I'm not sure how to support it. In any case, Vc works fine on the system (false positive). The code that inspects the generated assembly isn't able to cope with stack protector code.

**Comment by mattkretz** [comment]
See here: https://godbolt.org/g/vj3FYb

**Comment by mattkretz** [comment]
`-fstack-protector-all` should not lead to false negatives anymore now. I rewrote the test completely and found a minor performance issue that way.
