### ISSUE TITLE
Stream insertion operator of real_assert drops const qualifier

### ISSUE THREAD

**Issue by martin-hartl** [VcDevel/Vc#198]
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | Assembler & Version | CPU
----------------------|------------------|--------------------|----------------|---------------------|----
master                |  -                    | -                      |  -                 | -                     |   -

This member function drops the const qualifier of real_assert:
https://github.com/VcDevel/Vc/blob/eef0f1f0588a06fa28cfd0e8810472db5e610ebe/Vc/detail/detail.h#L70-L76

The tests build with default settings because `CMAKE_BUILD_TYPE` is set to `Release` which sets `NDEBUG` and disables these assertions.
With `CMAKE_BUILD_TYPE=Debug` the build fails.

**Comment by mattkretz** [comment]
It's actually already fixed in my branch:
https://github.com/VcDevel/Vc/blob/fd8d885a0f1594ed19c2c696658b805169d0373c/Vc/detail/detail.h#L88-94
