### ISSUE TITLE
CMake SSE3 detection with cpuinfo should look for pni

### ISSUE THREAD

**Issue by kmill** [VcDevel/Vc#199]
I came across this project randomly when researching SSE instructions, and I noticed that the CPU feature detection in [FindSSE.cmake](https://github.com/VcDevel/Vc/blob/master/cmake/FindSSE.cmake#L15) checks for SSSE3.  According to [this StackExchange answer](https://unix.stackexchange.com/questions/43539/what-do-the-flags-in-proc-cpuinfo-mean) it should be looking for `pni`.

Sorry for not following the template (it did not seem applicable for communicating this piece of information), and if I were to use this project I would submit a pull request myself.

**Comment by mattkretz** [comment]
Thank you. You're right about not following the template.
Note that FindSSE.cmake is unused. Your fix looks correct, but I better just remove the file than maintain untested code.
