### ISSUE TITLE
Vc::trunc() is broken with SSE2

### ISSUE THREAD

**Issue by amadio** [VcDevel/Vc#200]
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | Assembler & Version | CPU
----------------------|------------------|--------------------|----------------|---------------------|----
1.3.3            |      any          |       GCC7/Clang6          |      -msse2          |                     | skylake

## Testcase
```cpp
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <Vc/Vc>

int main(int argc, char **argv)
{
   float d = 1e10;

   Vc::float_v v(d);

   d = std::trunc(d);
   v = Vc::trunc(v);

   float v0 = v[0];

   printf("trunc(d) = %.16f\ntrunc(v) = %.16f\n", d, v0);

   return 0;
}
```

## Actual Results

```
$ c++ -Wall -msse2 -std=c++11 -O3 trunc.cc -lVc
$ ./a.out 
trunc(d) = 10000000000.0000000000000000
trunc(v) = 8589934592.0000000000000000
```

## Expected Results

```
$ c++ -Wall -msse4.2 -std=c++11 -O3 trunc.cc -lVc
$ ./a.out 
trunc(d) = 10000000000.0000000000000000
trunc(v) = 10000000000.0000000000000000
```

**Comment by mattkretz** [comment]
Thanks for the testcase. I'm working on reproducing it.

**Comment by amadio** [comment]
Hi Matthias, the same thing happens for `floor()` and `ceil()` functions in my tests.

**Comment by mattkretz** [comment]
Fixed. `trunc`, `floor`, `ceil` should also be considerably faster in the non-SSE4 case now.
