### ISSUE TITLE
Cannot compile Vc: make not working

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [VcDevel/Vc#201]
I am trying to compile the master branch of Vc on my system but `make` is not working and not giving any erorrs.
`cmake` ran fine with the only missing things being `Intel SDE not found` and `MIC SDK was not found!`. 

if I run:
```

$ ls
cmake  CMakeCache.txt  CMakeFiles  cmake_install.cmake  CTestCustom.cmake  Makefile
$ make
$
```
Then the prompt just returns nothing and no action is performed by `make`. Is the Makefile broken?

**Comment by ChukwuemezieChristopherAneke** [comment]
Thanks, I already confirmed that was the case.

**Comment by mattkretz** [comment]
For everything but releases, the `all` target includes building all unit tests. So, actually you should have gotten an hour long build... Note that master is going to change significantly soon. Stick with the 1.3 branch unless you're interested in contributing.

PS: Sorry for the late answer, vacation time...

**Comment by mattkretz** [comment]
I believe this issue can be closed, or did you expect any further action?
