### ISSUE TITLE
Ordering relations of `simd<T>`

### ISSUE THREAD

**Issue by gnzlbg** [VcDevel/Vc#204]
I'd expect the the following example to work:

```c++
std::vector<simd<int>> vec0, vec1;
// ...initialize vec0 and vec1...
assert(vec0 < vec1); //< Does this even work?
```

Since `operator<` for `simd<int>` returns a mask, whether that will work will depend on whether the mask is implicitly convertible to bool, and what the semantics of that are.

I can't find anything about ordering relations neither in the papers nor in the library implementation nor tests. Is this explained somewhere ? 

For example, if the implicit conversion to bool of the mask would test whether all elements of the mask are `true`, then `{0, 1, 2, 3}` is not smaller than `{0, 1, 2, 4}` because `{0, 1, 2, 3} < {0, 1, 2, 4}` returns the mask `{false, false, false, true}`, for which not all elements of the mask are `true`. 

That means that while `std::vector<int>{0, 1, 2, 3} < std::vector<int>{0, 1, 2, 4}` is `true`, the following would be false `std::vector<simd<int>>{{0, 1, 2, 3}} < std::vector<simd<int>>{{0, 1, 2, 4}}`.

Also, I could not find any discussion about which concepts the vector types implement anywhere (`SemiRegular`, `Regular`, etc.), and I would like to read about that, if possible.

**Comment by mattkretz** [comment]
https://wg21.link/p851r0

**Comment by mattkretz** [comment]
Hmm, why does it 404? http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0851r0.pdf

**Comment by mattkretz** [comment]
> Also, I could not find any discussion about which concepts the vector types implement anywhere (SemiRegular, Regular, etc.), and I would like to read about that, if possible.

The concepts were just added to the WD. IIRC `simd` would be SemiRegular.

**Comment by gnzlbg** [comment]
Thanks, that makes sense.
