### ISSUE TITLE
Incorrect values of Sin for large input values.

### ISSUE THREAD

**Issue by ArifAhmed1995** [VcDevel/Vc#206]
Vc version / revision : master branch

Operating System : Linux Ubuntu 18.04.1 LTS 

Compiler & Version : gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0

Compiler Flags : As done for test file([trigonometric.cpp](https://github.com/VcDevel/Vc/blob/1.3/tests/trigonometric.cpp#L56))

Assembler & Version :

CPU : Intel® Core™ i5-7200U CPU @ 2.50GHz × 4 (sse sse2 ssse3 sse4_1 sse4_2 avx avx2 supported)

Large input values might be fed to certain [Bessel integrals](https://en.wikipedia.org/wiki/Bessel_function#Bessel's_integrals), that's one case where such a need for accurate computation of `sin` and `cos` value of large numbers arises.

#### Modified the Sine test in [trigonometric.cpp](https://github.com/VcDevel/Vc/blob/1.3/tests/trigonometric.cpp#L56) file to the following (Added an array of large values, computed and displayed sine value of them.):
```
TEST_TYPES(V, testSin, (REAL_VECTORS, SIMD_REAL_ARRAY_LIST)) //{{{1
{
    typedef typename V::EntryType T;
    UnitTest::setFuzzyness<float>(2);
    UnitTest::setFuzzyness<double>(1e7);
    Array<SincosReference<T> > reference = sincosReference<T>();
    for (size_t i = 0; i + V::Size - 1 < reference.size; i += V::Size) {
        V x, sref, y;
        for (size_t j = 0; j < V::Size; ++j) {
            x[j] = reference.data[i + j].x;
            sref[j] = reference.data[i + j].s;
            y[j] = 1.3e20;
        }
        std::cout << Vc::sin(y) << std::endl;
        FUZZY_COMPARE(Vc::sin(x), sref) << " x = " << x << ", i = " << i;
        FUZZY_COMPARE(Vc::sin(-x), -sref) << " x = " << x << ", i = " << i;
    }
}
```

## Actual Results

For `trigonometric_sse`, `.._avx` and `.._avx2` :

```
.  
.  
<-9.13625e+32 -9.13625e+32 -9.13625e+32 -9.13625e+32 | -0.279659>
<-inf -inf -inf -inf | -0.838151>  
<-9.13625e+32 -9.13625e+32 -9.13625e+32 -9.13625e+32>  
<-inf -inf -inf -inf>  
<-9.13625e+32 -9.13625e+32 -0.279659>  
<-0.838151 -0.838151 -0.838151>  
.  
.  
```

For `trigonometric_scalar` :

```
[-0.279659]
[-0.838151]
<-0.279659 -0.279659 -0.279659>
<-0.838151 -0.838151 -0.838151>
<-0.279659>
<-0.838151>
```

## Expected Results

All values same and in between `[-1, 1]`.

Also, a similar issue exists for cosine as well.

**Comment by mattkretz** [comment]
Thanks for the report. Do I understand correctly, the double_v result is -9.13625e+32 and float_v yields -inf?

I'm wondering though, whether I really should make all of `sin`/`cos` more complex and thus slower. Consider what mathematica says:
```
N[Sin[1.3 *10^20]]
-0.279659
N[Sin[1.3 *10^20 - 2^66*Pi]]
0.713529
```
and mupad:
```
>> float(sin(1.3e20))
0.1455000338
>> float(sin(1.3e20-2^60*PI))
0.1455000338
>> float(sin(1.3e20-2^66*PI))
0.1455000338
```

Do you know what the correct result is? I believe the input is outside of the range of useful input values. Do you think a random value between `[-1, 1]` is better than obvious garbage?

Those are not rhetoric questions. I believe the `std::sin` result for `1.e20` inputs is garbage, but I don't know for certain. So if you know more, I want to know as well.

**Comment by mattkretz** [comment]
OK, I found that Mathematica prefers `13*10^19`, as it considers this notation exact. Using this, I believe Mathematica calculates it correctly. Consequently `std::sin(double)` still produces correct results for `10^20` inputs.

**Comment by mattkretz** [comment]
Consider we could improve the `double_v` implementation, what would you expect the `float_v` implementation to do? `std::sin(float)` certainly produces garbage.

**Comment by ArifAhmed1995** [comment]
I'll answer all the queries above as best as I can soon, but here's an observation.
With this test code :
```
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <Vc/Vc>

int main(int argc, char **argv)
{
   double d = 1.3e20;
   float f = 1.3e20;

   Vc::double_v v_double(d);
   Vc::float_v v_float(f);

   Vc::double_v v_d = Vc::sin(v_double);
   Vc::float_v v_f = Vc::sin(v_float);

   double std_d = std::sin(d);
   float std_f = std::sin(f);

   printf("std::sin(float) = %.16f\n"
           "std::sin(double) = %.16f\n"
           "Vc::sin(float) = %.16f\n"
           "Vc::sin(double) = %.16f\n", std_f, std_d, v_f[0], v_d[0]);

   return 0;
}
```

I get bogus results only when higher levels of optimization are done : `O1` included.

For `c++ -Wall -mavx2 -std=c++11 -O0 vc_test.cc -lVc` it seems to give reasonable results(the values don't match with that of std::sin though)

```
std::sin(float) = -0.8381511569023132
std::sin(double) = -0.2796593408795719
Vc::sin(float) = 0.3328270096338727
Vc::sin(double) = 1.0000000000000000
```

The same code, compiled with : `-O1` option instead, outputs :
```
std::sin(float) = -0.8381511569023132
std::sin(double) = -0.2796593408795719
Vc::sin(float) = -1404449098380955475234322914300996055709662671238761925787718904934553271061987809733949515273622290254316083048013475620522839186614683058470673966939041174575267919960895621099537250343993700853064490747389468947648813097004589806624863835668805672511319747995156650757167857546629613341258075283220594688.0000000000000000
Vc::sin(double) = 0.0000000000000000
```


Using `-ffast-math` with `-O0` gives similar results to without using `-ffast-math`.
Using `-Ofast` obviously yields those large bogus results.
Also, changing arch from `avx2` to others such as `sse2` or `avx` doesn't matter.

**Comment by ArifAhmed1995** [comment]
> Consider we could improve the `double_v` implementation, what would you expect the `float_v` implementation to do?

My current use case only requires the `double_v` to work correctly. I guess the `float_v` can be left for now, since `std::sin(float)` doesn't give correct results.

**Comment by ArifAhmed1995** [comment]
> Do you think a random value between `[-1, 1]` is better than obvious garbage?

No, neither will that work for my use case, nor do I see any use for that anywhere.

**Comment by mattkretz** [comment]
Careful with `%f` in `printf`: this requires a `double`, the ones printing floats are undefined behavior. Which kind of invalidates all of your output (once you start with UB, everything is undefined). In any case, if you want to print Vc::Vector subscripts with printf, better use a temporary `double` (e.g. `double(v_d[0])` should help).

I already know why the `sin(double_v)` implementation fails. When reducing the input into the `[0, 2pi]` range (actually `pi/4` and quadrant), the result of `input / (pi/4)` is off by ~6000, simply because double precision `pi/4` is not precise enough.

**Comment by mattkretz** [comment]
>>  Do you think a random value between [-1, 1] is better than obvious garbage?
>
> No, neither will that work for my use case, nor do I see any use for that anywhere.

OK, because you said "All values same and in between [-1, 1].". But the std::sin(float) result is obvious garbage, so that's why I asked. May I summarize your expectation then as: *If the std::sin result is correct, Vc::sin must be correct. Otherwise any result is fine.*?

The problem is that the results of `std::sin` are not overly well defined. At least when you consider portability between different stdlibs / hardware.

**Comment by ArifAhmed1995** [comment]
> May I summarize your expectation then as: If the std::sin result is correct, Vc::sin must be correct. Otherwise any result is fine.?

Yes, exactly. Sorry for any miscommunication earlier.

> The problem is that the results of std::sin are not overly well defined. At least when you consider portability between different stdlibs / hardware.

OKay, understood....

I'm actually working on some code in a library which involves `Bessel` functions.
Since they are defined for `(0, FLT_MAX)`, I was testing it out for large values. Have asked the library maintainers if such cases ever arise in practicality.
It seems to work with full precision equality for values as large as `1e5`.

**Comment by mattkretz** [comment]
> It seems to work with full precision equality for values as large as `1e5`.

That's a much saner range to support. However, I believe your expectation, that `Vc::sin` works equally well as `std::sin` for large inputs is something that needs fixing.
While looking into this I found a few more issues. Most important, my test data for double precision is incorrect.

**Comment by mattkretz** [comment]
Finally you can test something. Please take a look at the 1.4 branch. You have the option to use GNU's libmvec, which will fall back to std::sin and std::cos in some situations (so no speedup - e.g. without SSE4, or for large input values). Without libmvec you'll get my implementation, which is slower than before, but a lot more precise and with a larger supported input range.
I'll document the supported input ranges and their expected precision next.

**Comment by ArifAhmed1995** [comment]
@mattkretz My machine is currently under repair. Will test out once I get it back.
Thank you for fixing it !

**Comment by ArifAhmed1995** [comment]
@mattkretz So, I've tested out with `1.3e20` as [above](https://github.com/VcDevel/Vc/issues/206#issuecomment-412076274). `libmvec` is present on my system, since compiling with `-lmvec` doesn't throw up an error.
The values are different but not the same as `std` values:
```
std::sin(float) = -0.8381511569023132
std::sin(double) = -0.2796593408795719
Vc::sin(float) = -3349563212619880462926059929600.0000000000000000
Vc::sin(double) = 482287350574460813116729558153531549309468672.0000000000000000
```
Previously,
```
std::sin(float) = -0.8381511569023132
std::sin(double) = -0.2796593408795719
Vc::sin(float) = -1404449098380955475234322914300996055709662671238761925787718904934553271061987809733949515273622290254316083048013475620522839186614683058470673966939041174575267919960895621099537250343993700853064490747389468947648813097004589806624863835668805672511319747995156650757167857546629613341258075283220594688.0000000000000000
Vc::sin(double) = 0.0000000000000000
```
Do I have pass a manual flag to cmake ? From the commit it seems to be able to find it automatically.

**Comment by mattkretz** [comment]
To compile against libmvec you have to switch on the corresponding cmake option (e.g. via ccmake). 

I still don't care much for input values `double > 0x1.p50 ≈ 1e15` and `float > 0x1.p21 ≈ 2e6`. Those cutoffs are somewhat arbitrary, but in both cases the values have only 2 bits (or less) left for representation of fractional values. I.e. `sin(x)` and `sin(nextafter(x, inf))` are already far apart and cannot form a useful sine curve. Consider:

`limit=1e15; x=[limit:0.01:limit+4*pi]; plot(x-limit,sin(x));`
![grafik](https://user-images.githubusercontent.com/3306474/45016674-a139d300-b025-11e8-9490-097436266d23.png)

`limit=1e16; x=[limit:0.01:limit+4*pi]; plot(x-limit,sin(x));`
![grafik](https://user-images.githubusercontent.com/3306474/45016693-b7e02a00-b025-11e8-83bb-8ca37a66474e.png)

`limit=1e17; x=[limit:0.01:limit+4*pi]; plot(x-limit,sin(x));`
![grafik](https://user-images.githubusercontent.com/3306474/45016710-c75f7300-b025-11e8-8041-351d7ad96c1e.png)

This is plotted with GNU Octave, which, AFAIK, uses double precision for its representation.

**Comment by ArifAhmed1995** [comment]
Ah I understand, the resolution gets worse later on.
On the 1.4 branch it seems to work fine for much larger values than before and I don't think larger values that that are fed as input to the Bessel functions.
