### ISSUE TITLE
Compilation fails on unit test

### ISSUE THREAD

**Issue by jg110** [VcDevel/Vc#211]
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | Assembler & Version | CPU
----------------------|------------------|--------------------|----------------|---------------------|----
       9ea6a79     |   Fedora 28   |    GCC 8.1.1    |                |                  |  Intel Core i7-6500U

## Testcase
```cpp
```

## Actual Results
Compilation fails:
```Scanning dependencies of target simdarray_avx
[ 11%] Building CXX object tests/CMakeFiles/simdarray_avx.dir/simdarray.cpp.o
In file included from /home/user/repos/krita-dirs/vc/Vc/tests/simdarray.cpp:28:
/home/user/repos/krita-dirs/vc/Vc/tests/unittest.h:30:10: fatal error: virtest/vir/test.h: No such file or directory
 #include "virtest/vir/test.h"
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [tests/CMakeFiles/simdarray_avx.dir/build.make:379: tests/CMakeFiles/simdarray_avx.dir/simdarray.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:12641: tests/CMakeFiles/simdarray_avx.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

```
## Expected Results
Successful compilation

**Comment by mattkretz** [comment]
You need to do `git submodule update --init` after cloning Vc. If you know a standard way other build systems integrate git submodules, let me know.

**Comment by mattkretz** [comment]
hmm, at least I'll have to update the README. Will do

**Comment by jg110** [comment]
I should've looked at the README more closely, my apologies. I didn't see any submodules looking at the top directory and assumed it only required `cmake`, `make`, and `sudo make install`.

**Comment by mattkretz** [comment]
Yes, that's how it was just a few revisions ago. This was a very recent change. No need to apologize. ;-)
