### ISSUE TITLE
cmake: cmake macros fail without libmvec

### ISSUE THREAD

**Issue by Johnnynator** [VcDevel/Vc#215]
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | Assembler & Version | CPU
----------------------|------------------|--------------------|----------------|---------------------|----
 1.4.0                     |  Linux without libmvec e.g. Void musl, 686 or armv8  |  /  | / | / |

## Description

The libmvec check in the VcMacros seem to be fatal since it set's it as a required lib in L117 https://github.com/VcDevel/Vc/blob/1.4/cmake/VcMacros.cmake#L177.
Setting it not as a required but a optional lib or guarding it with a `if(Vc_LIB_MVEC)` after `find_library` may work.

## Actual Results
e.g. When compiling Krita:
https://www.travis-ci.com/Johnnynator/void-packages/jobs/151259698#L1182

## Expected Results

Not failing when detecting vc.
e.g. krita on a x86_64 system with glibc https://www.travis-ci.com/Johnnynator/void-packages/jobs/151259694#L1070

**Comment by mattkretz** [comment]
Thanks for the report. That's an unfortunate oversight. If libmvec is enabled then the lib is required, so that part is correct. But obviously it must work without libmvec. On it.

**Comment by mattkretz** [comment]
Please let me know whether this fixes it for you

**Comment by Johnnynator** [comment]
Thanks seems to work fine now.
