### ISSUE TITLE
krita build failure with Vc 1.4 (i586)

### ISSUE THREAD

**Issue by krop** [VcDevel/Vc#217]
We're seeing a build failure for the openSUSE's krita package if we try to build it with Vc 1.4.0.
Only the x86 build is affected.

Applying 81b3b1ad to the openVc package helped fixing the CMake error, but now I'm seeing a linker error:

```
[  519s] /usr/lib/gcc/i586-suse-linux/8/../../../../i586-suse-linux/bin/ld: CMakeFiles/kritapigment.dir/compositeops/KoOptimizedCompositeOpFactoryPerArch_Scalar.cpp.o: in function `_GLOBAL__sub_I_KoOptimizedCompositeOpFactoryPerArch_Scalar.cpp':
[  519s] /usr/include/Vc/cpuid.h:256: undefined reference to `Vc_1::CpuId::init()'
[  519s] /usr/lib/gcc/i586-suse-linux/8/../../../../i586-suse-linux/bin/ld: CMakeFiles/kritapigment.dir/KoOptimizedCompositeOpFactoryPerArch_SSE2.cpp.o: in function `_GLOBAL__sub_I_KoOptimizedCompositeOpFactoryPerArch_SSE2.cpp':
[  519s] /usr/include/Vc/cpuid.h:256: undefined reference to `Vc_1::CpuId::init()'
[  519s] /usr/lib/gcc/i586-suse-linux/8/../../../../i586-suse-linux/bin/ld: CMakeFiles/kritapigment.dir/KoOptimizedCompositeOpFactoryPerArch_SSSE3.cpp.o: in function `_GLOBAL__sub_I_KoOptimizedCompositeOpFactoryPerArch_SSSE3.cpp':
[  519s] /usr/include/Vc/cpuid.h:256: undefined reference to `Vc_1::CpuId::init()'
[  519s] /usr/lib/gcc/i586-suse-linux/8/../../../../i586-suse-linux/bin/ld: CMakeFiles/kritapigment.dir/KoOptimizedCompositeOpFactoryPerArch_SSE4_1.cpp.o: in function `_GLOBAL__sub_I_KoOptimizedCompositeOpFactoryPerArch_SSE4_1.cpp':
[  519s] /usr/include/Vc/cpuid.h:256: undefined reference to `Vc_1::CpuId::init()'
[  519s] /usr/lib/gcc/i586-suse-linux/8/../../../../i586-suse-linux/bin/ld: CMakeFiles/kritapigment.dir/KoOptimizedCompositeOpFactoryPerArch_AVX.cpp.o: in function `_GLOBAL__sub_I_KoOptimizedCompositeOpFactoryPerArch_AVX.cpp':
[  519s] /usr/include/Vc/cpuid.h:256: undefined reference to `Vc_1::CpuId::init()'
[  519s] /usr/lib/gcc/i586-suse-linux/8/../../../../i586-suse-linux/bin/ld: CMakeFiles/kritapigment.dir/KoOptimizedCompositeOpFactoryPerArch_AVX2+FMA+BMI2.cpp.o:/usr/include/Vc/cpuid.h:256: more undefined references to `Vc_1::CpuId::init()' follow
[  519s] collect2: error: ld returned 1 exit status
[  519s] make[2]: *** [libs/pigment/CMakeFiles/kritapigment.dir/build.make:890: libs/pigment/libkritapigment.so.17.0.0] Error 1
```
Full log available here: https://build.opensuse.org/project/monitor?utf8=%E2%9C%93&commit=Filter%3A&succeeded=1&failed=1&unresolvable=1&broken=1&blocked=1&dispatching=1&scheduled=1&building=1&finished=1&signing=1&locked=1&deleting=1&pkgname=&repo_openSUSE_Factory=1&arch_aarch64=1&arch_armv7l=1&arch_i586=1&arch_ppc64=1&arch_ppc64le=1&arch_s390x=1&arch_x86_64=1&project=home%3Acgiboudeaux%3Abranches%3Adevel%3Alibraries%3Ac_c%2B%2B&defaults=0

**Comment by wolfi323** [comment]
The reason is this (from Vc's build log on Factory/i586):
[   60s] CMake Warning at CMakeLists.txt:37 (message):
[   60s]   No optimized implementation of the Vc types available for i686

This PR would fix the CPU detection and as a result krita's build:
https://github.com/VcDevel/Vc/pull/190
This was included as patch in openSUSE's 1.3.x package (fix_i686_build.patch), but removed with the update to 1.4.0 in https://build.opensuse.org/request/show/641958 ...

The remaining question is why krita fails to build when there's no optimized implementation available.
Bug in krita or in Vc?

Btw, I remember seeing the same build failure when trying to build krita with Vc on PPC.

**Comment by krop** [comment]
Right, CMake sets Vc_X86 to FALSE, src/cpuid.cpp is not added to ${_srcs} and that causes the linker error.

**Comment by mattkretz** [comment]
@krop I believe the 1.4 branch should work for you now? I hope I'll be able to release 1.4.1 next week.

**Comment by krop** [comment]
The build still fails but that's not related to Vc anymore with your last change. Thanks !

**Comment by mattkretz** [comment]
Thanks for the quick feedback
