### ISSUE TITLE
Nightly builds of the documentation not accessible

### ISSUE THREAD

**Issue by pauljurczak** [VcDevel/Vc#221]
Clicking on any link to nightly builds of the documentation from the front page, gives me: `You don't have permission to access /~mkretz/Vc-1.4.1/ on this server.` message.

**Comment by mattkretz** [comment]
I see this too. But then sometimes it works again. Something is broken on GSI's personal pages. I need to move to a better place...

**Comment by mattkretz** [comment]
I moved all documentation to vcdevel.github.io now. You'll find the new links in an updated README.md.

**Comment by pauljurczak** [comment]
Thank you.

**Comment by mattkretz** [comment]
Thank you for helping out on the documentation! There's so much more to improve. Feel free to open issues for parts that you find unclear or missing!
