### ISSUE TITLE
size mismatch for Vc::uint32_v and Vc::float_v for -mavx

### ISSUE THREAD

**Issue by milianw** [VcDevel/Vc#226]
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | Assembler & Version | CPU
----------------------|------------------|--------------------|----------------|---------------------|----
1.4 / b725a903                      |  Linux                | g++ 8.2.1                   | Vc defaults               | GNU as 2.31.1                    |  Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz

## Testcase

https://godbolt.org/z/cFJIp2

## Actual Results

Vc::uint32_v::Size == 4 and Vc::float_v::Size == 8 for `-mavx`

## Expected Results

Vc::uint32_v::Size == 8 and Vc::float_v::Size == 8 for `-mavx`

Note that this works already for AVX2: https://godbolt.org/z/uNNKHq

**Comment by milianw** [comment]
It works for all configurations (scalar, sse2, sse3, sse41, sse42, avx2) but it doesn't work for avx...

**Comment by milianw** [comment]
in `vectorabi.h` there is this explicit code:

```
using Avx1Abi = typename std::conditional<std::is_integral<T>::value, VectorAbi::Sse,
                                          VectorAbi::Avx>::type;
```

Does this really mean that AVX has different vector sizes for 32bit ints vs. 32bit floats?

**Comment by milianw** [comment]
Looking at: https://software.intel.com/sites/landingpage/IntrinsicsGuide/#expand=3385,2239,4103,206,3500,3509,4103,206,185,206,182,176,200,197,200,194,4887,1291,1288,1335,1917,1954,45,106,1704,1707,1287,5273,1710,4873&techs=AVX&text=_mm256_set_ 

AVX has both, `_mm256_set_ps` which takes 8 floats and also `_mm256_set_epi32` which takes 8 ints. So why is this handled differently in Vc?

**Comment by milianw** [comment]
OK, looking at this query, it seems like AVX really is super broken for ints:

https://software.intel.com/sites/landingpage/IntrinsicsGuide/#expand=3385,2239,4103,206,3500,3509,4103,206,185,206,182,176,200,197,200,194,4887,1291,1288,1335,1917,1954,45,106,1704,1707,1287,5273,1710,4873&techs=AVX,AVX2&text=mm256_*epi32

tons of useful API only becomes available with AVX2, so that's probably the reason why the integer size is assumed to be less for AVX in Vc. I'll close this report.

**Comment by mattkretz** [comment]
Correct. Before Vc 1.0, I had `AVX::int_v::Size == AVX::float_v::Size` and it was not good for performance. If you have to use mixed arithmetic types I recommend the pattern:
```cpp
using float_v = Vc::float_v;
using int_v = Vc::simdize<int, float_v::size()>;
...
```

This will give you `Vc::Vector<int>` or `Vc::SimdArray<int, float_v::size()>` depending on the available ISA extensions.
