### ISSUE TITLE
Linking errors on Windows due to `/Gv`

### ISSUE THREAD

**Issue by milianw** [VcDevel/Vc#230]
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | Assembler & Version | CPU
----------------------|------------------|--------------------|----------------|---------------------|----
1.4                      |   Windows               |       Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27025.1 for x64             |   `Vc_COMPILE_FLAGS`             |                     |

## Testcase

Try to use Vc in a file that also uses and links against a non-vectorized library (e.g. Qt). 

Potentially related: https://github.com/VcDevel/Vc/issues/147

## Actual Results

Tons of linker errors in the form of:

```
tst_pipeline.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) void __vectorcall qBadAlloc(void)" (__imp_?qBadAlloc@@YQXXZ) referenced in function "public: __cdecl QVector<class QByteArray>::QVector<class QByteArray>(class std::initializer_list<class QByteArray>)" (??0?$QVector@VQByteArray@@@@QEAA@V?$initializer_list@VQByteArray@@@std@@@Z)
```

## Expected Results

No such linker errors. The errors arise from the `/Gv` that's added to `Vc_COMPILE_FLAGS`, cf. 65b58e79. 

Now, you may say: Don't use `Vc_COMPILE_FLAGS` in this case! Only use it while compiling  `Vc` itself. Well, that's also not an option, since then we can't use some of the non-decorated Vc API such as e.q.:

```
FooBar.lib(pipeline_simd_impl_AVX2+FMA+BMI2.cpp.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl Vc_1::CpuId::init(void)" (?init@CpuId@Vc_1@@SAXXZ)
```

Since now, Vc is compiled with `__vectorcall` as default, but when we use it, `__cdecl` will be the default again.

The only option I see is removing the `/Gv` flag altogether. I've tested it locally, and that works as expected for my use cases.

**Comment by mattkretz** [comment]
Without `__vectorcall`, passing a `Vc::Vector` type (or any composite type) by value is ill-formed. It is questionable, whether that's conforming to the C++ standard, but there's a [good line of argumentation for them not to support it](https://social.msdn.microsoft.com/Forums/vstudio/en-US/8fac034b-6ba4-478d-9130-8f6a56de368f/why-does-msvc-inhibit-the-use-of-aligned-types-as-function-parameters?forum=vclanguage#7bbaf8f9-103f-4b3b-857e-f723d945de58). At some point, in order to keep code compiling on MSVC I gave up trying and just started using `/Gv` to not have to bother anymore (supporting all the MSVC quirks took an enormous and already unreasonable amount of time). If you can make Vc reliable pass the AppVeyor CI without `/Gv` I'll be happy to merge a PR.

**Comment by DrPizza** [comment]
Seems that the answer is to compile without /Gv, but to instead add a `__vectorcall` to each function declaration.

**Comment by markstock** [comment]
I am experiencing this same problem (I think). My own C++ code is being compiled on MSVC with `/Gd` (`__cdecl` default) but needs to call functions from Vc (specifically reciprocal, atan2, rsqrt, and log) that have been built with `__vectorcall`. I see a similar link error:

`2>Simulation.obj : error LNK2019: unresolved external symbol "public: static class Vc_1::Vector<float,struct Vc_1::VectorAbi::Sse> __cdecl Vc_1::Common::Trigonometric<struct Vc_1::ImplementationT<4> >::atan2<class Vc_1::Vector<float,struct Vc_1::VectorAbi::Sse> >(class Vc_1::Vector<float,struct Vc_1::VectorAbi::Sse> const &,class Vc_1::Vector<float,struct Vc_1::VectorAbi::Sse> const &)" (??$atan2@V?$Vector@MUSse@VectorAbi@Vc_1@@@Vc_1@@@?$Trigonometric@U?$ImplementationT@$03@Vc_1@@@Common@Vc_1@@SA?AV?$Vector@MUSse@VectorAbi@Vc_1@@@2@AEBV32@0@Z) referenced in function "void __cdecl panels_affect_points$omp$1<float,float>(class Surfaces<float> const &,class Points<float> &)" (??$panels_affect_points$omp$1@MM@@YAXAEBV?$Surfaces@M@@AEAV?$Points@M@@@Z)`

It is strange that I only see this link error with `atan2` and not the others. And I am confused as to how to fix this. I presume I need an `extern ... __vectorcall ...` at the top of my source file (a template header file, actually), but there are so many decorations on `atan2` in Vc's `vector.h` file that I don't know where to begin. Can someone offer a suggestion?
