### ISSUE TITLE
Vectors of specific type and size.

### ISSUE THREAD

**Issue by max0x7ba** [VcDevel/Vc#231]
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | Assembler & Version | CPU
Vc-1.4.1
CentOS release 6.9
g++-6.3.0
Intel i7-4790

## Testcase
```cpp
    using Point4D = Vc::Vector<float, 4>;
    Point4D origin = {0,0,0,1};
```

## Actual Results
Fails to compile.

## Expected Results
Compiles and uses the right underlying type to represent a vector of 4 floats.

It should be equivalent to gcc code:
```
    typedef float v4f __attribute__ ((vector_size (16)));
    using Point4D = v4f;
    Point4D origin = {0,0,0,1};
```

**Comment by milianw** [comment]
That's handled by SimdArray, no?

https://vcdevel.github.io/Vc-1.4/group__SimdArray.html

**Comment by max0x7ba** [comment]
> That's handled by SimdArray, no?

That is what I need, thanks a lot.
