### ISSUE TITLE
1.4.2 - The dashboard may not show any failures

### ISSUE THREAD

**Issue by agheata** [VcDevel/Vc#263]
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | Assembler & Version | CPU
----------------------|------------------|--------------------|----------------|---------------------|----
        1.4.2              |          all        |          all          |       -         |          -           |

## Testcase
```cpp
```

## Actual Results
Dashboard [status](http://lxwww53.gsi.de/index.php?project=Vc)
## Expected Results
No failures

**Comment by agheata** [comment]
The dashboard as of Dec 14, 2020 only shows few warnings,  non-critical for the tag.

**Comment by bernhardmgruber** [comment]
Dashboard looks good: https://cdash.cern.ch/index.php?project=Vc
