### ISSUE TITLE
1.4.2 - Documentation up to date

### ISSUE THREAD

**Issue by agheata** [VcDevel/Vc#265]
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | Assembler & Version | CPU
----------------------|------------------|--------------------|----------------|---------------------|----
         1.4.2             |        all          |       all             |      -          |           -          |

## Testcase
```cpp
```

## Expected Results
Documentation builds without (bad) warnings and it is not outdated

**Comment by agheata** [comment]
Building the documentation locally, it produces a number of warnings in few categories. It remains to be defined if they are 'bad' or acceptable:

```/Users/agheata/geant_src/Vc/Vc/common/const.h:66: warning: no matching file member found for 
constexpr double exponentToFloat(std::integral_constant< bool, false > negative)
Possible candidates:
 'constexpr double exponentToFloat(std::integral_constant< bool, true >)' at line 71 of file /Users/agheata/geant_src/Vc/Vc/common/const.h
 'constexpr double exponentToFloat(std::integral_constant< bool, false >)' at line 66 of file /Users/agheata/geant_src/Vc/Vc/common/const.h
/Users/agheata/geant_src/Vc/Vc/common/simdarray.h:551: warning: no matching file member found for 
void gatherImplementation(const Common::GatherArguments< MT, IT, Scale > &args)
Possible candidates:
 'void gatherImplementation(const Common::GatherArguments< MT, IT, Scale > &)' at line 56 of file /Users/agheata/geant_src/Vc/Vc/common/gatherinterface.h
 'void gatherImplementation(const Common::GatherArguments< MT, IT, Scale > &, MaskArgument mask)' at line 63 of file /Users/agheata/geant_src/Vc/Vc/common/gatherinterface.h
/Users/agheata/geant_src/Vc/Vc/common/simdarray.h:2387: warning: no matching file member found for 
enable_if<(N !=M &&(offset *Return::Size< Common::left_size< N >)) &&offset !=0 &&(offset+1) *Return::Size > Common::left_size< N >())
Possible candidates:
 'typename std::enable_if< Test, T >::type enable_if' at line 48 of file /Users/agheata/geant_src/Vc/Vc/traits/type_traits.h
...
```
```
/Users/agheata/geant_src/Vc/Vc/common/simdarray.h:2441: warning: member with no name found.
```
```
/Users/agheata/geant_src/Vc/Vc/common/simdmaskarray.h:357: warning: @copybrief or @copydoc target 'Mask::value_type' not found
/Users/agheata/geant_src/Vc/doc/dox.h:286: warning: unable to resolve reference to 'Vc_IMPL_Scalar' for \ref command
```
```
/Users/agheata/geant_src/Vc/Vc/common/simdarray.h:1721: warning: parameters of member Vc::operator+ are not (all) documented
/Users/agheata/geant_src/Vc/Vc/common/simdarray.h:1721: warning: return type of member Vc::operator+ is not documented
```
In many cases it seems that doxygen does not manage to resolve correctly template symbols, but there are also warnings due to missing \return, \param, ...

**Comment by bernhardmgruber** [comment]
> ```
> constexpr double exponentToFloat(std::integral_constant< bool, false > negative)
> Possible candidates:
>  'constexpr double exponentToFloat(std::integral_constant< bool, true >)' at line 71 of file /Users/agheata/geant_src/Vc/Vc/common/const.h
>  'constexpr double exponentToFloat(std::integral_constant< bool, false >)' at line 66 of file /Users/agheata/geant_src/Vc/Vc/common/const.h
> /Users/agheata/geant_src/Vc/Vc/common/simdarray.h:551: warning: no matching file member found for 
> void gatherImplementation(const Common::GatherArguments< MT, IT, Scale > &args)
> Possible candidates:
>  'void gatherImplementation(const Common::GatherArguments< MT, IT, Scale > &)' at line 56 of file /Users/agheata/geant_src/Vc/Vc/common/gatherinterface.h
>  'void gatherImplementation(const Common::GatherArguments< MT, IT, Scale > &, MaskArgument mask)' at line 63 of file /Users/agheata/geant_src/Vc/Vc/common/gatherinterface.h
> /Users/agheata/geant_src/Vc/Vc/common/simdarray.h:2387: warning: no matching file member found for 
> enable_if<(N !=M &&(offset *Return::Size< Common::left_size< N >)) &&offset !=0 &&(offset+1) *Return::Size > Common::left_size< N >())
> Possible candidates:
>  'typename std::enable_if< Test, T >::type enable_if' at line 48 of file /Users/agheata/geant_src/Vc/Vc/traits/type_traits.h
> ...
> ```

I looked into these and I think doxygen is confused because these functions are members of a class in one header, but their inline implementations are pulled in from other header files.

> ```
> /Users/agheata/geant_src/Vc/Vc/common/simdmaskarray.h:357: warning: @copybrief or @copydoc target 'Mask::value_type' not found
> /Users/agheata/geant_src/Vc/doc/dox.h:286: warning: unable to resolve reference to 'Vc_IMPL_Scalar' for \ref command
> ```

Many of these warnings come from doxygen failing to parse the referenced entity because of a surrounding `Vc_DEPRECATED` macro.

Generally, the documentation builds and looks fine (short inspection).
