### ISSUE TITLE
1.4.2 - Release notes

### ISSUE THREAD

**Issue by agheata** [VcDevel/Vc#267]
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | Assembler & Version | CPU
----------------------|------------------|--------------------|----------------|---------------------|----
         1.4.2             |        all          |         all           |                |                     |

## Testcase
```cpp
```

## Expected Results
Release notes summarizing the full changelog and closed issues

**Comment by agheata** [comment]
The relevant closed issues since 1.4.1 seem to be: #221 , #226 , #228 , #231 , #232,  #247 , #250 , #253

**Comment by agheata** [comment]
A pointer to previous release notes would be useful to have.

**Comment by bernhardmgruber** [comment]
I drafted the release notes on the release page here based on the statements of previous releases: https://github.com/VcDevel/Vc/releases.
Also all closed issues and PRs are now correctly tagged with the Vc 1.4.2 milestone.
