### ISSUE TITLE
1.4.2 - Upload docs, qch, and tarball to the release page

### ISSUE THREAD

**Issue by agheata** [VcDevel/Vc#268]
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | Assembler & Version | CPU
----------------------|------------------|--------------------|----------------|---------------------|----
         1.4.2             |          all        |          all          |       -         |          -           |

## Testcase
```cpp
```

## Expected Results
* Run the makeRelease.sh script.
* Upload docs, qch, and tarball to the release page on GitHub.
* Check that the full changelog is still up to date.
* Extract the docs tarball on web server.

**Comment by agheata** [comment]
makeRelease.sh does not work for me, it gets stuck at the step:
```Cloning into 'vcdevel.github.io'...
...
ERROR: Permission to VcDevel/vcdevel.github.io.git denied to agheata.
fatal: Could not read from remote repository.
```

**Comment by bernhardmgruber** [comment]
I reached @mattkretz today and he had another look at the permissions. @Axel-Naumann just succeeded with `makeRelease.sh` and the new documentation and the artifacts for the github release are online. The 1.4.2 tag is also there.
