### ISSUE TITLE
Warning from find_package(Vc) with CMake 3.19

### ISSUE THREAD

**Issue by rmatev** [VcDevel/Vc#270]
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | Assembler & Version | CPU
----------------------|------------------|--------------------|----------------|---------------------|----
1.4.1                      |  CentOS 7                |   gcc 9                 |                |                     |

There is a new warning from `find_package(Vc)` when configuring a project with CMake 3.19.1, which seems to be coming from https://github.com/VcDevel/Vc/blob/37d48ab7d2bdc9481fb43ec00ec5c4c3527a20a7/cmake/VcMacros.cmake#L35 (see example below). Would it be possible to increase the minimum version there?

```
CMake Deprecation Warning at /cvmfs/lhcb.cern.ch/lib/lcg/releases/LCG_97a/Vc/1.4.1/x86_64-centos7-gcc9-opt/lib/cmake/Vc/VcMacros.cmake:35 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  /cvmfs/lhcb.cern.ch/lib/lcg/releases/LCG_97a/Vc/1.4.1/x86_64-centos7-gcc9-opt/lib/cmake/Vc/VcConfig.cmake:36 (include)
  Det/DetDesc/CMakeLists.txt:21 (find_package)
```

**Comment by davidrohr** [comment]
I am getting the same warnings, and would appreciate if we could have a new release with this fixed.

**Comment by agheata** [comment]
@rmatev or @davidrohr can you review if #276 fixes the problem in your build?
