### ISSUE TITLE
Vc_DEFINITIONS vairable exprted by FindVc.cmake should be Vc_COMPILE_OPTIONS

### ISSUE THREAD

**Issue by dokempf** [VcDevel/Vc#28]
Despite its name, the variable `Vc_DEFINITIONS` does not contain compile definitions but other compiler flags: `-march=core2 -msse2 -msse2 -msse3 -msse3 -mssse3 etc.`

This results in broken compiler calls if processed as definitions, like:
`set_property(TARGET target APPEND PROPERTY COMPILE_DEFINITIONS ${Vc_DEFINITIONS})`

**Comment by mkret2** [comment]
You are right. The variable got conflated at some point. I don't want to change `Vc_DEFINITIONS` in the 0.7 branch (to not break anyones code). I would be very happy for a patch against master to solve this for 1.0, though. I'm not 100% sure yet how I'd like to have it broken up. But I think `DEFINTIONS` vs. `COMPILE_FLAGS` should do.
