### ISSUE TITLE
The MSVC detection artifact is missing from release builds

### ISSUE THREAD

**Issue by amyspark** [VcDevel/Vc#287]
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | Assembler & Version | CPU
----------------------|------------------|--------------------|----------------|---------------------|----
 1.4.2                     |      Windows            |         MSVC 19.29.30038.1           |       `/MD /O1 /Ob1 /DNDEBUG /fp:fast`         |   N/A                  | Ryzen 7 2700x

## Testcase

```cpp
#include <Vc/Vc>
#include <Vc/support.h>
#include <iostream>

int main() {
   return 0;
}
```

```cmake
cmake_minimum_required(VERSION 3.10)

project (test)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(Vc 1.3.0 REQUIRED)

add_executable(main main.cpp)

target_compile_options(main PRIVATE "/fp:fast")

target_link_libraries(main PUBLIC Vc::Vc)
```

## Actual Results

CMake finds and instantiates `Vc::Vc`, but log shows that MSVC version detection fails:

```
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_PREFIX_PATH:STRING=E:\VcDevel\install -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_INSTALL_PREFIX:STRING=e:/VcDevelTest/install -He:/VcDevelTest/src -Be:/VcDevelTest/build -G "Visual Studio 16 2019" -T host=x64 -A x64
[cmake] Not searching for unused variables given on the command line.
[cmake] -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
[cmake] msvc_version.c
[cmake] c1: fatal error C1083: No se puede abrir el archivo origen: 'E:/VcDevel/install/lib/cmake/Vc/msvc_version.c': No such file or directory
[cmake] -- Detected Compiler: MSVC 
[cmake] -- Detected CPU: zen
[cmake] -- Configuring done
[cmake] -- Generating done
[cmake] -- Build files have been written to: E:/VcDevelTest/build
```

## Expected Results

Compilation and linking successful with no errors.

**Comment by bernhardmgruber** [comment]
I had a look into why this file is actually needed and it seems it is only used to detect the last version of Visual Studio 2013 (`_MSC_FULL_VER` 180021114), which is the first version where Vc apparently works. If we just require Visual Studio 2015, we can eliminate the entire detection logic for `_MSC_FULL_VER` and just use CMake's builtin `MSVC_VERSION`. Given VS2015 is around for quite some time, this seems more reasonable to me.

**Comment by amyspark** [comment]
@bernhardmgruber can I work on it?

**Comment by bernhardmgruber** [comment]
Seems I was faster: #290. But feel free to add comments and suggestions!
