### ISSUE TITLE
Regenerate Compiler Explorer header for 1.4.2 and onwards

### ISSUE THREAD

**Issue by amyspark** [VcDevel/Vc#296]
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | Assembler & Version | CPU
----------------------|------------------|--------------------|----------------|---------------------|----
1.4.2 |  Compiler Explorer |         N/A  | N/A | N/A | N/A

## Testcase

<https://godbolt.org/z/f76oj8316>

```cpp
#include <https://raw.githubusercontent.com/VcDevel/Vc/1.4/godbolt/Vc>
#include <limits>
#include <string>

int main() {
    const std::string test = Vc_VERSION_STRING;
    return 0;
}

```

## Actual Results

```
.L.str:
        .asciz  "1.4.1-dev"
```

## Expected Results

```
.L.str:
        .asciz  "1.4.3-dev"
```

**Comment by bernhardmgruber** [comment]
That is indeed outdated. Compiler Explorer is super useful. I think we should at least regenerate the file from the 1.4.2 release. I added a comment to the release procedure: https://github.com/VcDevel/Vc/wiki/Releases-Checklist

Furthermore, we could consider automatically generating the file on each commit.
