### ISSUE TITLE
Vc does not compile

### ISSUE THREAD

**Issue by vks** [VcDevel/Vc#30]
I tried to compile d257efbc42daf1120a5f47237f49d82c62ccb23b on Linux with gcc 5.2.0:

```
[...]
~/src/Vc/common/simdarray.h:501:9: error: non-constant condition for static assertion
         static_assert(init.size() == size(), "The initializer_list argument to "
         ^
[...]
```

See [the full error message](https://gist.github.com/vks/eff0ce5526218e89917f) for details.

**Comment by mattkretz** [comment]
I have already "fixed" this on 'mkretz/gh-11 AVX2 support' in 685cfff6230e3eb44c154dc4f199248f3f7353af. I'll see to get this merged soon.

**Comment by mattkretz** [comment]
the fix is now on master
