### ISSUE TITLE
cannot compile for MIC

### ISSUE THREAD

**Issue by kehw** [VcDevel/Vc#31]
I tied to build Vc for MIC with icc 15.0.1, commit d257efb. 
The following errors raise for both the CPU (target Vc) side and MIC side (target Vc_MIC).
```
In file included from /home/kehw/hlt/Vc/mic/../common/../traits/type_traits.h(38),
                 from /home/kehw/hlt/Vc/mic/../common/types.h(38),
                 from /home/kehw/hlt/Vc/mic/../common/loadstoreflags.h(32),
                 from /home/kehw/hlt/Vc/mic/intrinsics.h(41),
                 from /home/kehw/hlt/Vc/src/mic_sorthelper.cpp(29):
/home/kehw/hlt/Vc/mic/../common/../traits/is_functor_argument_immutable.h(41): error: type name is not allowed
      typedef decltype(&F::template operator()<A>) type;
                                               ^

In file included from /home/kehw/hlt/Vc/mic/../common/../traits/type_traits.h(38),
                 from /home/kehw/hlt/Vc/mic/../common/types.h(38),
                 from /home/kehw/hlt/Vc/mic/../common/loadstoreflags.h(32),
                 from /home/kehw/hlt/Vc/mic/intrinsics.h(41),
                 from /home/kehw/hlt/Vc/src/mic_sorthelper.cpp(29):
/home/kehw/hlt/Vc/mic/../common/../traits/is_functor_argument_immutable.h(41): error: expected an expression
      typedef decltype(&F::template operator()<A>) type;
                                                 ^
```

In addition, in the file cmake/FindMIC.cmake, you mentioned that 
```
   # For now offload is not supported so skip it
```
Does this mean we can not build Vc in offload mode?

**Comment by mattkretz** [comment]
> I tied to build Vc for MIC with icc 15.0.1

You should update your ICC. 15.0.1 is rather old by now. 15.0.3 and 16.0.0 are the most recent ones I can support. Though if 15.0.3 fails to parse valid C++ which 16.0.0 understands then I'll drop support for 15 altogether.
The situation could be different if there were a dedicated maintainer for ICC support. But as it stands, the regular breakage introduced from ICC bugs is just too much to handle for me alone.

> Does this mean we can not build Vc in offload mode?

Maybe. "not supported" means it might just work, but I'm not actively ensuring that it works. Again, not enough manpower.

**Comment by kehw** [comment]
Thank you for the explanation. I tried icc 15.0.4 today and it compiles the libraries with the following failed tests

         16 - stlcontainer_mic (Failed)
         28 - arithmetics_mic (Failed)
         38 - load_avx (Failed)
         65 - math_mic (Failed)
         77 - utils_mic (Failed)
         81 - sorted_mic (Failed)
         89 - deinterleave_mic (Failed)
        100 - simdarray_scalar (Failed)
        101 - simdarray_sse (Failed)
        102 - simdarray_avx (SEGFAULT)
        103 - simdarray_mic (Failed)

**Comment by mattkretz** [comment]
That sound about right for ICC on master. This doesn't mean Vc is unusable, only that some special corner cases might miscompile. (Again, manpower issue...)

Please just open a new issue if you have a specific bug you need to have fixed.
