### ISSUE TITLE
I followed all the installation instructions, but I can't run #include <Vc/Vc>.

### ISSUE THREAD

**Issue by heteloo** [VcDevel/Vc#311]
| Vc version / revision | Operating System  | Compiler & Version | Compiler Flags                                                                                         | Assembler & Version | CPU             |
|-----------------------|-------------------|--------------------|--------------------------------------------------------------------------------------------------------|---------------------|-----------------|
| 1.4.2                 | ubuntu vscode c++ | g++ 11             | /usr/bin/g++-11 -fdiagnostics-color=always -g /home/user/projectt/test.cpp -o /home/user/projectt/test |                     | amd ryzen 1600x |

## Testcase
```cpp
#include <Vc/Vc>
#include <iostream>


int main(){
    std::cout << "Hello World" << std::endl;
}
```

## Actual Results
/home/user/projectt/test.cpp:1:10: fatal error: Vc/Vc: No such file or directory
    1 | #include <Vc/Vc>
      | ^~~~~~~~~
compilation terminated.

The build completed, but an error occurred.
## Expected Results
Helloworld

## additional attempts
I haven't used cmake.
(I'm not sure how to use it.)

#include "Vc/Vc"
Syntax like , didn't help either.

order of commands executed
1. cd
2. git clone https://github.com/VcDevel/Vc
3. cd Vc
4. git submodule update --init
5. cd
6. mkdir build
7. cd build
8. cmake -DCMAKE_INSTALL_PREFIX=/opt/Vc -DBUILD_TESTING=OFF "/home/user/Vc"

**Comment by bernhardmgruber** [comment]
I see you installed Vc into `/opt/Vc`, which is not the standard installation directory of cmake.

Depending on the build system for your hello world example, if you use CMake, you may need to specify `Vc_DIR` and point it to your Vc installation for cmake to find it. If you use makefiles you are probably missing `-I` and `-L` arguments for your compiler/linker to find the Vc headers and library.

**Comment by amadio** [comment]
This does not look like a problem in Vc. Feel free to continue to discuss a solution for you here, but I will close this issue for the moment. You need to add either `-I/opt/Vc/include` to your compilation if you are compiling by hand, or add `-DCMAKE_PREFIX_PATH=/opt/Vc` in case you are using CMake to build your project.
