### ISSUE TITLE
cmake selects the wrong MSVC compiler

### ISSUE THREAD

**Issue by ypoissant** [VcDevel/Vc#323]
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | Assembler & Version | CPU
----------------------|------------------|--------------------|----------------|---------------------|----
origin/1.4            |Windows 10          |MSVC 14.31.31103    |                |                     |i7 8700

I followed the instruction for installing Vc. When running "cmake -DCMAKE_INSTALL_PREFIX=/opt/Vc -DBUILD_TESTING=OFF .." in the build folder, the first output I get is "Building for: Visual Studio 16 2019" and a little bit later, I get this: "WARNING! MSVC starting with 19.20 uses a new optimizer that has a bug causing Vc::exp() to return slighly wrong results. ..."

I have two VS versions installed: VS 16 2019 and VS 17 2022. I would like to build for VS 2022 hoping this would fix the "wrong results" issue. I checked that the "path" variable and all related environment variables all point to the VS 2022 toolset folder but somehow, cmake still finds the wrong compiler. How can I explicitly direct cmake to use the proper compiler? Which file do I need to modify and how? Or do I need to uninstall VS 2019?

**Comment by bernhardmgruber** [comment]
Hi! The instructions in the README.md are Linux oriented. I updated it to add some hints for Windows as well: https://github.com/VcDevel/Vc/pull/324

In your case, you will need to pass a generator argument to CMake:
```sh
cmake -G "Visual Studio 16 2019" -DBUILD_TESTING=OFF ..
```

Also note, that we have not added VS 2022 to the CI yet, because the compiler crashes compiling the unit tests. You can give it a try though!

**Comment by amadio** [comment]
Closing this, since #324 has been merged already. Thank you @bernhardmgruber!
