### ISSUE TITLE
porting Vc code to highway

### ISSUE THREAD

**Issue by kfjahnke** [VcDevel/Vc#331]
I have written adapter code which mimicks Vc::SimdArray but internally uses highway to do the SIMD operations. This is to help my applications [vspline](https://bitbucket.org/kfj/vspline) and [lux](https://bitbucket.org/kfj/pv) widen their scope, the code in question is [here](https://bitbucket.org/kfj/pv/src/master/vspline/hwy_simd_type.h) and there's an [issue with highway](https://github.com/google/highway/issues/641). The implementation works in the context of my code, but of course it's not a complete replacement and it's still fresh and not well-tested, nevertheless I thought Vc users may find the approach interesting.
While writing the wrapper I noticed that highway does not currently provide an atan2 implementation. I added a quick shot implementation to my class template, but a 'proper' port to highway would be desirable. I proceeded to adapt Vc's atan2 routine from trigonometric.cpp to use highway internally, keeping the variable names and logic. I'd like to make this code available, but I don't want to violate your copyright or license, and I'm not sure how 'original' or 'derived' one might consider my work. Can you advise me? I'll share the code here if you like.

**Comment by bernhardmgruber** [comment]
Thank you for raising your work to our attention. Vc is licensed under [BSD-3-Clause](https://github.com/VcDevel/Vc/blob/1.4/LICENSE). If you started from Vc's implementation of atan2, then your work is a derived work and thus requires you to reproduce the BSD-3-Clause license header with the copyright statement from [trigonometric.cpp](https://github.com/VcDevel/Vc/blob/1.4/src/trigonometric.cpp).

Pinging @mattkretz for his opinion.

**Comment by kfjahnke** [comment]
@bernhardmgruber: Thank you for your prompt reply!
I have uploaded my port to my bitbucket repository, please have a look at:
https://bitbucket.org/kfj/pv/src/master/vspline/hwy_atan2.h
and let me know whether you think the original work's copyright and licensing are honoured correctly.
@jan-wassenberg: There is also code copied and pasted from highway's math-inl.h, can you please check and let me know whether you consider your copyright and licensing are honoured correctly.

**Comment by jan-wassenberg** [comment]
@kfjahnke I am not a lawyer so this is not legal advice, but the Highway portions are short and very generic so I don't see a problem there.
One small observation: you could use the NaN(d) function instead of Set(d, qnan).

**Comment by bernhardmgruber** [comment]
@kfjahnke I think you don't need to reproduce the original Vc code in your header. The BSD header should be sufficient. Thank you!

**Comment by kfjahnke** [comment]
Okay, fine, with both the highway and Vc sides not objecting to my licensing, I'll leave it at that. I'll leave the Vc code in for now, just for reference, so it's clear how I arrived at the highway port from the Vc code. Thank you for getting back to me, I'll close this issue.
