### ISSUE TITLE
howto install on Fedora 21

### ISSUE THREAD

**Issue by Pshemas** [VcDevel/Vc#45]
First of all - I have ZERO knowledge on what's "build" / "cmake" etc. Consider a dumb user here. I'm trying to install Vc on Fedora 21 as it is needed by one of the packages I wish to use.

I'm stuck at:
"Call cmake with the relevant options"

What are relevant options?

**Comment by Pshemas** [comment]
ok , after a bit of juggling with arguments I got it. First I need to create a folder where I create the install (separate folder from the folder with source - of course ;) ), then go to it and run

cmake -DCMAKE_INSTALL_PREFIX=/folder_where_in_the_end_app_will_be_installed -DBUILD_TESTING=OFF /folder_containing_source_files

Then:
$ make -j9
$ make install

**Comment by mattkretz** [comment]
exactly. Another important option is ``CMAKE_BUILD_TYPE``. You can also use ``ccmake`` or ``cmake-gui`` to get an overview of the available switches.
