### ISSUE TITLE
1.0 and .75 compatibility with Vc::tie()

### ISSUE THREAD

**Issue by miabrahams** [VcDevel/Vc#46]
Hello, I am attempting to build Krita with Vc 1.0 support and ran into a bit of confusion. This Vc .75 code interleaves some data. (The data types are `struct Pixel {float r, g, b, a;};` and `Vc::float_v src_c1, src_c2, ...` ) 

```
const Vc::uint_v indexes(Vc::IndexesFromZero);
Vc::InterleavedMemoryWrapper<Pixel, Vc::float_v> data(const_cast<Pixel*>(sp));
(src_c1, src_c2, src_c3, src_alpha) = data[indexes];
```

This failed to compile on Vc 1.0.  Just inspecting example code I got it working by substituting the type in the first line, and adding `Vc::tie()` in the last line.

```
const Vc::float_v::IndexType indexes(Vc::IndexesFromZero);
Vc::InterleavedMemoryWrapper<Pixel, Vc::float_v> data(const_cast<Pixel*>(sp));
tie(src_c1, src_c2, src_c3, src_alpha) = data[indexes];
```

I think the change in the first line is acceptable in both versions, but the fix in the last line is problematic since Vc::tie() is not defined. We can't drop support for compiling the older version, since we want to build on Windows with MSVC 2015. My idea is that perhaps that dropping the tie() could work in Vc 1.0, but that results in this template error.

``` 
error: no match for ‘operator=’ (operand types are ‘Vc_0::float_v {aka Vc_0::Vector<float, Vc_0::VectorAbi::Sse>}’ and ‘Vc_0::enable_if<true, Vc_0::Common::InterleavedMemoryAccess<4ul, Vc_0::Vector<float, Vc_0::VectorAbi::Sse>, Vc_0::SimdArray<int, 4ul, Vc_0::Vector<int, Vc_0::VectorAbi::Sse>, 4ul> > > {aka Vc_0::Common::InterleavedMemoryAccess<4ul, Vc_0::Vector<float, Vc_0::VectorAbi::Sse>, Vc_0::SimdArray<int, 4ul, Vc_0::Vector<int, Vc_0::VectorAbi::Sse>, 4ul> >}’) 
```

**Comment by mattkretz** [comment]
Actually, this should have compiled without `Vc::tie`, and printed a deprecation warning. I think I broke this when `Vector` moved directly into the `Vc` namespace.

Once I fix this, you'll get a deprecation warning with 1.0. What you could try in any case is:
```
#if VC_VERSION_CHECK(0, 99, 71) >= VC_VERSION_NUMBER
#define TIE tie
#else
#define TIE
#endif
```

**Comment by miabrahams** [comment]
Thanks for the quick fix, by the way!
