### ISSUE TITLE
problem with Vc_ARCHITECTURE_FLAGS

### ISSUE THREAD

**Issue by kehw** [VcDevel/Vc#59]
When using the Vc library, if I add Vc_ARCHITECTURE_FLAGS into compiler flags I have the following error
```
/include/Vc/avx/helperimpl.h(32): catastrophic error: cannot open source file "sse/helperimpl.h"
  #include "sse/helperimpl.h"
                             ^
```

Vc_INCLUDE_DIR has been added to include_directories.

**Comment by mattkretz** [comment]
Thanks for the report. I hope my commit solves it. Let me know if not.
