### ISSUE TITLE
Unknown CMake command "add_compile_options".

### ISSUE THREAD

**Issue by vks** [VcDevel/Vc#69]
While trying to setup the Travis build bot for Vc, I ran into the following issue:

```
CMake Error at CMakeLists.txt:117 (add_compile_options):

  Unknown CMake command "add_compile_options".
```

Travis uses cmake 2.8.11.2. Does Vc require a newer version? If so, it should probably check for that in the build script.

**Comment by mattkretz** [comment]
I have actually no clue what cmake version Vc requires. I'm missing this information in the cmake documentation. :-(
I could just bump the version requirement to the lowest cmake version I have working somewhere as a safe bet. Any idea how to get this right?

**Comment by vks** [comment]
It seems like it was introduced in cmake 3.0 ([here](https://cmake.org/cmake/help/v3.0/command/add_compile_options.html) is the first occurence I could find).

**Comment by mattkretz** [comment]
Thanks!
