### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [VcDevel/Vc#73]
I would like to point out that identifiers like "[`Vc_DECLARE_BINARY_FUNCTION__`](https://github.com/VcDevel/Vc/blob/1c52fde7148dd68adadc15ec5694a98add8ff5d9/common/simdarray.h#L54)" and "[`VC_VECTOR__`](https://github.com/VcDevel/Vc/commit/66ef75ee5d07a2430d7382a61ee78746a00834c9#diff-fe673f580b0aa95ba306c08745b7174cR24)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by mattkretz** [comment]
Ouch, I failed to recognize that double underscores are reserved regardless of whether they are prefixes or not.

BTW, there is no "expected naming convention of the C++ language standard". You probably want to talk about *reserved to the implementation*.

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/VcDevel/Vc/commit/40307b1827dc5d9b2fac135e45267f61dd68d295 "Deletion of some underscores").
