### ISSUE TITLE
Several math operations don't work on SimdArray

### ISSUE THREAD

**Issue by chr-engwer** [VcDevel/Vc#75]
Trying to play with the `SimdArray<T,N>` I immediatelly stubled upon the fact that `Vc::sqrt(.)` does not for `SimdArray<T,N>`. As the documentation is a bit scarce, I'm not sure whether I used it correctly, but I would have assumed, that I can use them the same way as I use the underlying Vector<T>. It seems that there is a mechanism to support arbitrary operations on the `SimdArray<T,N>`, but again I was not able to figure it out from the current documentation.

**Comment by mattkretz** [comment]
Yes, sorry. I should have mentioned that `SimdArray<T>` is not yet on feature parity with `Vector<T>`. It's supposed to be. I'd be happy for pull requests here. This is mostly boring copy and paste work.

**Comment by chr-engwer** [comment]
@mattkretz I would have provided a patch, if it would be clear how things are to be implemented. As the current state is totally undocumented, it is not clear to me how the two implementations of `SimdArray<T,N>` actually differ and what the intended way to implement such features is. Is there an operator which is working and which can serve as an example? Is it necessary to specialize the operators for the two implementations, or can this be done for both at once? Is there some black magic to get the loop over the underlying `Vector<T>`?

**Comment by mattkretz** [comment]
Yes, I'll improve the documentation on how `SimdArray` is implemented right away. You can find `abs`, `isnan`, `frexp`, and `ldexp` examples in `common/simdarray.h` (and `simdarrayhelper.h`). I.e. don't worry how `SimdArray` is implemented. I developed an abstraction to easily implement the interface with underlying `Vector<T>`.

**Comment by chr-engwer** [comment]
Thanks for the pointers, I'll have a look.

**Comment by chr-engwer** [comment]
OK, this is indeed straight forward. I started by implementing the sqrt, I think I will add more operators on demand:  chr-engwer/Vc@b6a4ee196bfdf5b7e713350ed622759b9d65e0ff

**Comment by chr-engwer** [comment]
In the corresponding pull request #77 I implemented the first additional operator and it **is** straight forward. I added a very short test case, but in general it would be good to factor out the tests from vector and reuse the same tests for the

**Comment by mattkretz** [comment]
Seems to be working with clang now. GCC on my systems breaks down with an internal error in its error routine... best error to be had - not.

**Comment by mattkretz** [comment]
Merged to master. All functions that are tested in `math.cpp` are now tested on `SimdArray` as well. If you have any other missing function, please report or send a pull request.
