### ISSUE TITLE
Compilation error in math.cpp with icc (ICC) 15.0.3 20150407

### ISSUE THREAD

**Issue by peremato** [VcDevel/Vc#8]
Hi,
See the following error. Is this a problem with ICC or the test can be improved?
```
[ 15%] Building CXX object math/vc/tests/CMakeFiles/math_scalar.dir/math.cpp.o
/mnt/build/jenkins/workspace/root-nightly-master/BUILDTYPE/Release/COMPILER/icc15/LABEL/slc6/root/math/vc/include/Vc/scalar/math.h(204): error: the global scope has no "isfinite"
              ::isfinite(x.data())
                ^
          detected during instantiation of "void testInf<Vec>() [with Vec=ROOT::Vc::float_v]" at line 915 of "/mnt/build/jenkins/workspace/root-nightly-master/BUILDTYPE/Release/COMPILER/icc15/LABEL/slc6/root/math/vc/tests/math.cpp"

compilation aborted for /mnt/build/jenkins/workspace/root-nightly-master/BUILDTYPE/Release/COMPILER/icc15/LABEL/slc6/root/math/vc/tests/math.cpp (code 2)
make[2]: *** [math/vc/tests/CMakeFiles/math_scalar.dir/math.cpp.o] Error 2
make[1]: *** [math/vc/tests/CMakeFiles/math_scalar.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by mkret2** [comment]
In theory there is no `isfinite` in C++98. C++11 added `std::isfinite` and C99 added `::isfinite`. C99 is not part of C++98...
Maybe the most sensible solution at this point (it's 2015 anyway) is to disable all `isfinite` functionality without C++11? What do you think?

**Comment by peremato** [comment]
Hi Matthias,

  For what concerns ROOT, we build always with C++11 now (both branches 5 and 6).
  Cheers,

Pere

On 08 Jul 2015, at 08:26, Matthias Kretz <notifications@github.com<mailto:notifications@github.com>> wrote:


In theory there is no isfinite in C++98. C++11 added std::isfinite and C99 added ::isfinite. C99 is not part of C++98...
Maybe the most sensible solution at this point (it's 2015 anyway) is to disable all isfinite functionality without C++11? What do you think?

—
Reply to this email directly or view it on GitHub<https://github.com/VcDevel/Vc/issues/8#issuecomment-119451891>.

-------------------------------------------------------------
Pere Mato  CERN, PH Department, CH 1211 Geneva 23, Switzerland
e-mail: pere.mato@cern.ch<mailto:pere.mato@cern.ch> tel:   +41 22 76 78696
fax:  +41 22 76 68792 gsm: +41 75 41 10855
