### ISSUE TITLE
Conditional evaluations partially broken

### ISSUE THREAD

**Issue by chr-engwer** [VcDevel/Vc#90]
According to http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4185.pdf `Vc::iif` should work for `bool` and any `Vc` mask type.
> For the Vc library, I defined the function
> ```
>    Vector<T> iif(Mask<T>, Vector<T>, Vector<T>).
> ```
>The name `iif` is an abbreviation for `inline-if`. To allow generic use of this function, Vc provides the overloadT `iif(bool, T, T)`. Thus `iif` can be used in template functions where both `bool`s and `Vc` mask types may be used as the first argument to `iif`.

This does not work as expected:
  * Vc::iif fail for plain types
  * Vc::iif fails for fully specified `SimdArray` with non-default architecture
  * Vc::iif works for `Vector`
  * Vc::iif works for default `SimdArray`

Here is a short test program to reproduce the problem:
```C++
#include <Vc/Vc>

template<typename T>
void test_conditional()
{
    using std::sqrt;
    using std::abs;
    T a;
    T b = Vc::iif( (a>1.0), abs(a), sqrt(a));
}

int main ()
{
    // fails! // test_conditional<double>();
    test_conditional<Vc::Vector<double>>();
    test_conditional<Vc::Vector<double, Vc::VectorAbi::Scalar>>();
    test_conditional<Vc::SimdArray<double,2>>();
    // fails! // test_conditional<Vc::SimdArray<double,2,Vc::Vector<double, Vc::VectorAbi::Scalar>,1>>();
    return 0;
}
```

**Comment by mattkretz** [comment]
I still don't follow exactly why it fails for plain `double`. But I'll take a closer look later. The fully specified `SimdArray` type (non-default) probably is due to a too restrictive `is_simd_vector<T>` trait implementation.

**Comment by chr-engwer** [comment]
Did you try it? It fails as follows:

`typename enable_if<is_simd_vector<Mask>::value>, typename assert_for_iif<T>::type>::type`
has to evaluate the ??? in order to provide the correct type, this has to be done, even if `is_simd_vector<T>::value` is false (like for bool). Then `assert_for_iif` checks that T is a vector, which abviously wrong for `double`. If I move the assert into the `iif` body, the static_assert is not evaluated for the (failing) declaration, but only for the instantiation, which is never performed, due to SFINAE.

**Comment by mattkretz** [comment]
I believe you that it's broken. I'm a bit concerned that I apparently failed to write a unit test for builtin types with `iif`. I also wondered why I wrote it the way I did. Seems like I tried to work around the "static_assert breaks SFINAE" issue - though I don't see that this could solve it. I'll finish #75 first. Then I'll take a closer look.

**Comment by chr-engwer** [comment]
Regarding the `SimdArray`, the problem is not the `is_simd_vector<T>::value`. The issue is somewhere deeper below. It is a missing implementation for some type of conditional assignement:
```
common/where.h:62:153: error: no matching function for call to 'conditional_assign(Vc_1::SimdArray<double, 2ul, Vc_1::Vector<double, Vc_1::VectorAbi::Scalar>, 1ul>&, const Mask&, const Vc_1::SimdArray<double, 2ul, Vc_1::Vector<double, Vc_1::VectorAbi::Scalar>, 1ul>&)'
```
Perhaps it is not implemented because of the tricky problems with non-matching sizes?

**Comment by mattkretz** [comment]
OK, yes. The combinatorics can be an issue here (like for `simd_cast`). But there should be some way to have a generic fallback that's maybe not 100% optimal in all cases but at least compilers & works correctly.

**Comment by mattkretz** [comment]
* The `conditional_assign` issue was simple.
* The `static_assert` vs. SFINAE issue is not solvable. But my favorite pattern at this point is to use a deleted function to convey the intention to the user. Can't write custom diagnostics, though... :-(
