### ISSUE TITLE
Is Vc for XeonPhi broken? - commit 85c3531

### ISSUE THREAD

**Issue by calebepb** [VcDevel/Vc#93]
Hi Mathias,

I think last commit (85c3531) broke compilation for XeonPhi:
<code>
.../include/Vc/mic/vector.tcc(587): error: call of an object of a class type without appropriate operator() or conversion functions to pointer-to-function type
</code>
<code>
      return _mm512_getexp_ps(x.data()());
</code>

I could compile using commit 78a43c3.
I'am using icc-15.0.3 (gcc 4.8.3)

Best.

**Comment by mattkretz** [comment]
Thanks for the report! I'm on it. Saw it on the dashboard as well.
