### ISSUE TITLE
Vc::Vector<long int> doesn't work

### ISSUE THREAD

**Issue by amadio** [VcDevel/Vc#94]
The simple code below does not compile for me using AVX2:

```cpp
#include <Vc/Vc>
int main(int argc, char *argv[])
{
  Vc::Vector<long> var;
  return 0;
}
```

I am compiling with `g++ -Wall -std=c++11 -march=native test.cc -lVc` on a machine with AVX2.
Compilation works if I use SSE explicitly, but fails again if I try with the code below (initializing with a zero):

```cpp
#include <Vc/Vc>
int main(int argc, char *argv[])
{
  Vc::Vector<long> var(0);
  return 0;
}
```

**Comment by mattkretz** [comment]
At this point only `double`, `float`, `(un)signed int`, and `(un)signed short` are supported. Some functions may work for other arithmetic types, but if they do it is more or less luck.
I'd love to see Vc supporting more integral types (like @paulelsner's work on adding `uchar` support). If you'd like to give it a shot I can help you along.

**Comment by amadio** [comment]
Thanks for the quick answer. It would be nice to have a table of what is supported for each architecture.
At the moment, the README file states that Vc can be compiled for AVX2, but it doesn't mention that support is incomplete.

**Comment by amadio** [comment]
Another thing to be considered is to provide a generic implementation that uses scalar emulation to allow users to target `Vc::Vector<long int>` and be able to compile their code and run it while support is not there yet, or at least make the compiler provide a clear error message when a user uses an unsupported type.

**Comment by mattkretz** [comment]
Depending on your definition of "complete", Vc will likely always be incomplete. I fully agree that the documentation needs work. I would be happy for suggestions, especially in patch/pull request form.
