### ISSUE TITLE
add uchar support

### ISSUE THREAD

**Issue by mattkretz** [VcDevel/Vc#95]
@paulelsner started this in 431b6bf1d355a7703045f800e39a7bf2768c8570. This needs to be finished and merged to master.
- [ ] resolve the comments attached to the commit
- [ ] implement `simd_cast`s
- [ ] extend all unit tests to also test `uchar_v`

**Comment by mattkretz** [comment]
Moving to 2.0, because I'm actually implementing it there.

**Comment by paulelsner** [comment]
Thanks, currently I have no time available for the project.

**Comment by mattkretz** [comment]
@paulelsner Yeah, sorry that it is taking so long and that I wasn't able to merge your effort yet. With Vc 2.0 I'm taking a shot at complete arithmetic types support (i.e. 8 to 64 bit integers and `float`, `double`, and `long double`, though the latter doesn't vectorize for obvious reasons).

**Comment by mattkretz** [comment]
uchar support (actually *all* integer types) is implemented and working in the mkretz/datapar branch
